export const EMOJI_DATA: { [key: string]: { name: string; keywords: string[] } } = {
  '😀': { name: 'grinning face', keywords: ['face', 'smile', 'happy', 'joy', '😀'] },
  '😃': { name: 'grinning face with big eyes', keywords: ['face', 'happy', 'joy', 'haha', '😃'] },
  '😄': { name: 'grinning face with smiling eyes', keywords: ['face', 'happy', 'joy', 'funny', 'haha', 'laugh', 'like', '😄'] },
  '😁': { name: 'beaming face with smiling eyes', keywords: ['face', 'happy', 'smile', 'joy', '😁'] },
  '😆': { name: 'grinning squinting face', keywords: ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'laugh', '😆'] },
  '😅': { name: 'grinning face with sweat', keywords: ['face', 'hot', 'happy', 'laugh', 'sweat', 'smile', 'relief', '😅'] },
  '😂': { name: 'face with tears of joy', keywords: ['face', 'cry', 'tears', 'weep', 'happy', 'haha', 'joy', '😂'] },
  '🤣': { name: 'rolling on the floor laughing', keywords: ['face', 'rolling', 'lol', 'laughing', 'haha', '🤣'] },
  '😊': { name: 'smiling face with smiling eyes', keywords: ['face', 'smile', 'happy', 'flushed', 'crush', 'good', '😊'] },
  '😇': { name: 'smiling face with halo', keywords: ['face', 'angel', 'heaven', 'halo', '😇'] },
  '🙂': { name: 'slightly smiling face', keywords: ['face', 'smile', '🙂'] },
  '🙃': { name: 'upside-down face', keywords: ['face', 'silly', 'sarcasm', '🙃'] },
  '😉': { name: 'winking face', keywords: ['face', 'happy', 'mischievous', 'secret', 'wink', '😉'] },
  '😌': { name: 'relieved face', keywords: ['face', 'relaxed', 'phew', 'massage', 'happiness', '😌'] },
  '😍': { name: 'smiling face with heart-eyes', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart', '😍'] },
  '🥰': { name: 'smiling face with hearts', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'hearts', '🥰'] },
  '😘': { name: 'face blowing a kiss', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss', '😘'] },
  '😗': { name: 'kissing face', keywords: ['love', 'like', 'face', '3', 'valentines', 'infatuation', 'kiss', '😗'] },
  '😙': { name: 'kissing face with smiling eyes', keywords: ['face', 'affection', 'valentines', 'infatuation', 'kiss', '😙'] },
  '😚': { name: 'kissing face with closed eyes', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss', '😚'] },
  '😋': { name: 'face savoring food', keywords: ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', '😋'] },
  '😛': { name: 'face with tongue', keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'tongue', '😛'] },
  '😝': { name: 'squinting face with tongue', keywords: ['face', 'prank', 'playful', 'mischievous', 'tongue', '😝'] },
  '😜': { name: 'winking face with tongue', keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'wink', 'tongue', '😜'] },
  '🤪': { name: 'zany face', keywords: ['face', 'goofy', 'crazy', '🤪'] },
  '🤨': { name: 'face with raised eyebrow', keywords: ['face', 'skeptical', 'suspicious', '🤨'] },
  '🧐': { name: 'face with monocle', keywords: ['face', 'stuffy', 'wealthy', '🧐'] },
  '🤓': { name: "nerd face", keywords: ["face", "nerdy", "geek", "dork", "🤓"] },
  '😎': { name: "smiling face with sunglasses", keywords: ["face", "cool", "sunglasses", "😎"] },
  '🤩': { name: "star-struck", keywords: ["face", "star", "eyes", "grinning", "🤩"] },
  '🥳': { name: "partying face", keywords: ["face", "party", "hat", "celebration", "🥳"] },
  '😏': { name: "smirking face", keywords: ["face", "smirk", "smug", "😏"] },
  '😒': { name: "unamused face", keywords: ["face", "unamused", "annoyed", "😒"] },
  '😞': { name: "disappointed face", keywords: ["face", "sad", "disappointed", "😞"] },
  '😔': { name: "pensive face", keywords: ["face", "sad", "pensive", "😔"] },
  '😟': { name: "worried face", keywords: ["face", "worried", "nervous", "😟"] },
  '😕': { name: "confused face", keywords: ["face", "confused", "uncertain", "😕"] },
  '🙁': { name: "slightly frowning face", keywords: ["face", "sad", "frowning", "🙁"] },
  '☹️': { name: "frowning face", keywords: ["face", "sad", "frowning", "☹️"] },
  '😣': { name: "persevering face", keywords: ["face", "struggling", "persevering", "😣"] },
  '😖': { name: "confounded face", keywords: ["face", "confounded", "struggling", "😖"] },
  '😫': { name: "tired face", keywords: ["face", "tired", "exhausted", "😫"] },
  '😩': { name: "weary face", keywords: ["face", "weary", "exhausted", "😩"] },
  '🥺': { name: "pleading face", keywords: ["face", "pleading", "begging", "🥺"] },
  '😢': { name: "crying face", keywords: ["face", "sad", "crying", "😢"] },
  '😭': { name: "loudly crying face", keywords: ["face", "sad", "crying", "😭"] },
  '😤': { name: "face with steam from nose", keywords: ["face", "angry", "triumph", "😤"] },
  '😠': { name: "angry face", keywords: ["face", "angry", "mad", "😠"] },
  '😡': { name: "pouting face", keywords: ["face", "angry", "pouting", "😡"] },
  '🤬': { name: "face with symbols on mouth", keywords: ["face", "swearing", "cursing", "🤬"] },
  '🤯': { name: "exploding head", keywords: ["face", "shocked", "mind blown", "🤯"] },
  '😳': { name: "flushed face", keywords: ["face", "flushed", "blushing", "😳"] },
  '🥵': { name: "hot face", keywords: ["face", "hot", "sweating", "🥵"] },
  '🥶': { name: "cold face", keywords: ["face", "cold", "freezing", "🥶"] },
  '😱': { name: "face screaming in fear", keywords: ["face", "scream", "fear", "😱"] },
  '😨': { name: "fearful face", keywords: ["face", "fear", "scared", "😨"] },
  '😰': { name: "anxious face with sweat", keywords: ["face", "anxious", "nervous", "😰"] },
  '😥': { name: "sad but relieved face", keywords: ["face", "sad", "relieved", "😥"] },
  '😓': { name: "downcast face with sweat", keywords: ["face", "sad", "sweat", "😓"] },
  '🤗': { name: "hugging face", keywords: ["face", "hug", "🤗"] },
  '🤔': { name: "thinking face", keywords: ["face", "thinking", "🤔"] },
  '🤭': { name: "face with hand over mouth", keywords: ["face", "oops", "giggle", "🤭"] },
  '🤫': { name: "shushing face", keywords: ["face", "shush", "quiet", "🤫"] },
  '🤥': { name: "lying face", keywords: ["face", "lie", "pinocchio", "🤥"] },
  '😶': { name: "face without mouth", keywords: ["face", "silent", "quiet", "😶"] },
  '😐': { name: "neutral face", keywords: ["face", "neutral", "😐"] },
  '😑': { name: "expressionless face", keywords: ["face", "expressionless", "😑"] },
  '😬': { name: "grimacing face", keywords: ["face", "grimace", "awkward", "😬"] },
  '🙄': { name: "face with rolling eyes", keywords: ["face", "rolling eyes", "annoyed", "🙄"] },
  '😯': { name: "hushed face", keywords: ["face", "hushed", "surprised", "😯"] },
  '😦': { name: "frowning face with open mouth", keywords: ["face", "frowning", "surprised", "😦"] },
  '😧': { name: "anguished face", keywords: ["face", "anguished", "pained", "😧"] },
  '😮': { name: "face with open mouth", keywords: ["face", "surprised", "shocked", "😮"] },
  '😲': { name: "astonished face", keywords: ["face", "astonished", "shocked", "😲"] },
  '🥱': { name: "yawning face", keywords: ["face", "yawn", "tired", "🥱"] },
  '😴': { name: "sleeping face", keywords: ["face", "sleep", "zzz", "😴"] },
  '🤤': { name: "drooling face", keywords: ["face", "drool", "🤤"] },
  '😪': { name: "sleepy face", keywords: ["face", "sleepy", "tired", "😪"] },
  '😵': { name: "dizzy face", keywords: ["face", "dizzy", "😵"] },
  '🤐': { name: "zipper-mouth face", keywords: ["face", "zip", "secret", "🤐"] },
  '🥴': { name: "woozy face", keywords: ["face", "woozy", "dizzy", "🥴"] },
  '🤢': { name: "nauseated face", keywords: ["face", "nauseous", "sick", "🤢"] },
  '🤮': { name: "face vomiting", keywords: ["face", "vomit", "sick", "🤮"] },
  '🤧': { name: "sneezing face", keywords: ["face", "sneeze", "sick", "🤧"] },
  '😷': { name: "face with medical mask", keywords: ["face", "mask", "sick", "😷"] },
  '🤒': { name: "face with thermometer", keywords: ["face", "thermometer", "sick", "🤒"] },
  '🤕': { name: "face with head-bandage", keywords: ["face", "bandage", "injured", "🤕"] },
  '🤑': { name: "money-mouth face", keywords: ["face", "money", "rich", "🤑"] },
  '🤠': { name: "cowboy hat face", keywords: ["face", "cowboy", "hat", "🤠"] },
  '😈': { name: 'smiling face with horns', keywords: ['face', 'devil', 'evil', '😈'] },
  '👿': { name: 'angry face with horns', keywords: ['face', 'devil', 'evil', '👿'] },
  '👹': { name: 'ogre', keywords: ['monster', 'fantasy', '👹'] },
  '👺': { name: 'goblin', keywords: ['monster', 'fantasy', '👺'] },
  '🤡': { name: 'clown face', keywords: ['face', 'clown', 'circus', '🤡'] },
  '💩': { name: 'pile of poo', keywords: ['poop', 'dung', '💩'] },
  '👻': { name: 'ghost', keywords: ['halloween', 'spooky', '👻'] },
  '💀': { name: 'skull', keywords: ['death', 'skeleton', '💀'] },
  '☠️': { name: 'skull and crossbones', keywords: ['death', 'danger', '☠️'] },
  '👽': { name: 'alien', keywords: ['extraterrestrial', 'ufo', '👽'] },
  '👾': { name: 'alien monster', keywords: ['game', 'retro', '👾'] },
  '🤖': { name: 'robot', keywords: ['android', 'cyborg', '🤖'] },
  '🎃': { name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin', '🎃'] },
  '😺': { name: 'grinning cat', keywords: ['cat', 'animal', '😺'] },
  '😸': { name: 'grinning cat with smiling eyes', keywords: ['cat', 'animal', '😸'] },
  '😹': { name: 'cat with tears of joy', keywords: ['cat', 'animal', '😹'] },
  '😻': { name: 'smiling cat with heart-eyes', keywords: ['cat', 'animal', '😻'] },
  '😼': { name: 'cat with wry smile', keywords: ['cat', 'animal', '😼'] },
  '😽': { name: 'kissing cat', keywords: ['cat', 'animal', '😽'] },
  '🙀': { name: 'weary cat', keywords: ['cat', 'animal', '🙀'] },
  '😿': { name: 'crying cat', keywords: ['cat', 'animal', '😿'] },
  '😾': { name: 'pouting cat', keywords: ['cat', 'animal', '😾'] },
  '👋': { name: 'waving hand', keywords: ['wave', 'hello', 'goodbye', '👋'] },
  '🤚': { name: 'raised back of hand', keywords: ['hand', 'raised', '🤚'] },
  '🖐️': { name: 'hand with fingers splayed', keywords: ['hand', 'fingers', 'splayed', '🖐️'] },
  '✋': { name: 'raised hand', keywords: ['hand', 'raised', '✋'] },
  '🖖': { name: 'vulcan salute', keywords: ['hand', 'vulcan', 'spock', '🖖'] },
  '👌': { name: 'ok hand', keywords: ['hand', 'ok', '👌'] },
  '🤏': { name: 'pinching hand', keywords: ['hand', 'pinching', '🤏'] },
  '✌️': { name: 'victory hand', keywords: ['hand', 'victory', 'peace', '✌️'] },
  '🤞': { name: 'crossed fingers', keywords: ['hand', 'luck', '🤞'] },
  '🤟': { name: 'love-you gesture', keywords: ['hand', 'love', '🤟'] },
  '🤘': { name: 'sign of the horns', keywords: ['hand', 'rock', '🤘'] },
  '🤙': { name: 'call me hand', keywords: ['hand', 'call', '🤙'] },
  '👈': { name: 'backhand index pointing left', keywords: ['hand', 'point', 'left', '👈'] },
  '👉': { name: 'backhand index pointing right', keywords: ['hand', 'point', 'right', '👉'] },
  '👆': { name: 'backhand index pointing up', keywords: ['hand', 'point', 'up', '👆'] },
  '🖕': { name: 'middle finger', keywords: ['hand', 'middle finger', '🖕'] },
  '👇': { name: 'backhand index pointing down', keywords: ['hand', 'point', 'down', '👇'] },
  '☝️': { name: 'index pointing up', keywords: ['hand', 'point', 'up', '☝️'] },
  '👍': { name: 'thumbs up', keywords: ['hand', 'like', '👍'] },
  '👎': { name: 'thumbs down', keywords: ['hand', 'dislike', '👎'] },
  '👊': { name: 'oncoming fist', keywords: ['hand', 'fist', 'punch', '👊'] },
  '✊': { name: 'raised fist', keywords: ['hand', 'fist', 'protest', '✊'] },
  '🤛': { name: 'left-facing fist', keywords: ['hand', 'fist', '🤛'] },
  '🤜': { name: 'right-facing fist', keywords: ['hand', 'fist', '🤜'] },
  '👏': { name: 'clapping hands', keywords: ['hand', 'clap', '👏'] },
  '🙌': { name: 'raising hands', keywords: ['hand', 'celebration', '🙌'] },
  '👐': { name: 'open hands', keywords: ['hand', 'open', '👐'] },
  '🤲': { name: 'palms up together', keywords: ['hand', 'prayer', '🤲'] },
  '🤝': { name: 'handshake', keywords: ['hand', 'agreement', '🤝'] },
  '🙏': { name: 'folded hands', keywords: ['hand', 'prayer', 'thanks', '🙏'] },
  '✍️': { name: 'writing hand', keywords: ['hand', 'write', '✍️'] },
  '💅': { name: 'nail polish', keywords: ['hand', 'beauty', '💅'] },
  '🤳': { name: 'selfie', keywords: ['hand', 'phone', '🤳'] },
  '💪': { name: 'flexed biceps', keywords: ['muscle', 'strong', '💪'] },
  '🦾': { name: 'mechanical arm', keywords: ['robot', 'prosthetic', '🦾'] },
  '🦿': { name: 'mechanical leg', keywords: ['robot', 'prosthetic', '🦿'] },
  '🦵': { name: 'leg', keywords: ['kick', '🦵'] },
  '🦶': { name: 'foot', keywords: ['kick', '🦶'] },
  '👂': { name: 'ear', keywords: ['hear', 'listen', '👂'] },
  '🦻': { name: 'ear with hearing aid', keywords: ['hearing', 'disability', '🦻'] },
  '👃': { name: 'nose', keywords: ['smell', '👃'] },
  '🧠': { name: 'brain', keywords: ['mind', 'smart', '🧠'] },
  '🦷': { name: 'tooth', keywords: ['dentist', '🦷'] },
  '🦴': { name: 'bone', keywords: ['skeleton', '🦴'] },
  '👀': { name: 'eyes', keywords: ['look', 'see', '👀'] },
  '👁️': { name: 'eye', keywords: ['look', 'see', '👁️'] },
  '👅': { name: 'tongue', keywords: ['taste', '👅'] },
  '👄': { name: 'mouth', keywords: ['kiss', 'lips', '👄'] },
  '💋': { name: 'kiss mark', keywords: ['lips', 'love', '💋'] },
  '🐶': { name: 'dog face', keywords: ['animal', 'pet', '🐶'] },
  '🐱': { name: 'cat face', keywords: ['animal', 'pet', '🐱'] },
  '🐭': { name: 'mouse face', keywords: ['animal', 'pet', '🐭'] },
  '🐹': { name: 'hamster', keywords: ['animal', 'pet', '🐹'] },
  '🐰': { name: 'rabbit face', keywords: ['animal', 'pet', 'bunny', '🐰'] },
  '🦊': { name: 'fox', keywords: ['animal', '🦊'] },
  '🐻': { name: 'bear', keywords: ['animal', '🐻'] },
  '🐼': { name: 'panda', keywords: ['animal', 'bear', '🐼'] },
  '🐨': { name: 'koala', keywords: ['animal', 'bear', '🐨'] },
  '🐯': { name: 'tiger face', keywords: ['animal', 'cat', '🐯'] },
  '🦁': { name: 'lion', keywords: ['animal', 'cat', 'king', '🦁'] },
  '🐮': { name: 'cow face', keywords: ['animal', 'farm', '🐮'] },
  '🐷': { name: 'pig face', keywords: ['animal', 'farm', '🐷'] },
  '🐽': { name: 'pig nose', keywords: ['animal', 'farm', '🐽'] },
  '🐸': { name: 'frog', keywords: ['animal', 'amphibian', '🐸'] },
  '🐵': { name: 'monkey face', keywords: ['animal', 'primate', '🐵'] },
  '🙈': { name: 'see-no-evil monkey', keywords: ['animal', 'monkey', '🙈'] },
  '🙉': { name: 'hear-no-evil monkey', keywords: ['animal', 'monkey', '🙉'] },
  '🙊': { name: 'speak-no-evil monkey', keywords: ['animal', 'monkey', '🙊'] },
  '🐒': { name: 'monkey', keywords: ['animal', 'primate', '🐒'] },
  '🐔': { name: 'chicken', keywords: ['animal', 'bird', 'farm', '🐔'] },
  '🐧': { name: 'penguin', keywords: ['animal', 'bird', '🐧'] },
  '🐦': { name: 'bird', keywords: ['animal', '🐦'] },
  '🐤': { name: 'baby chick', keywords: ['animal', 'bird', 'baby', '🐤'] },
  '🐣': { name: 'hatching chick', keywords: ['animal', 'bird', 'baby', '🐣'] },
  '🐥': { name: 'front-facing baby chick', keywords: ['animal', 'bird', 'baby', '🐥'] },
  '🦆': { name: 'duck', keywords: ['animal', 'bird', '🦆'] },
  '🦅': { name: 'eagle', keywords: ['animal', 'bird', '🦅'] },
  '🦉': { name: 'owl', keywords: ['animal', 'bird', 'wise', '🦉'] },
  '🦇': { name: 'bat', keywords: ['animal', 'mammal', '🦇'] },
  '🐺': { name: 'wolf', keywords: ['animal', 'mammal', '🐺'] },
  '🐗': { name: 'boar', keywords: ['animal', 'mammal', '🐗'] },
  '🐴': { name: 'horse face', keywords: ['animal', 'mammal', '🐴'] },
  '🦄': { name: 'unicorn', keywords: ['animal', 'mythical', '🦄'] },
  '🐝': { name: 'honeybee', keywords: ['insect', 'bee', '🐝'] },
  '🐛': { name: 'bug', keywords: ['insect', 'caterpillar', '🐛'] },
  '🦋': { name: 'butterfly', keywords: ['insect', '🦋'] },
  '🐌': { name: 'snail', keywords: ['mollusk', '🐌'] },
  '🐞': { name: 'lady beetle', keywords: ['insect', 'ladybug', '🐞'] },
  '🐜': { name: 'ant', keywords: ['insect', '🐜'] },
  '🦟': { name: 'mosquito', keywords: ['insect', '🦟'] },
  '🦗': { name: 'cricket', keywords: ['insect', '🦗'] },
  '🕷️': { name: 'spider', keywords: ['arachnid', '🕷️'] },
  '🕸️': { name: 'spider web', keywords: ['arachnid', '🕸️'] },
  '🦂': { name: 'scorpion', keywords: ['arachnid', '🦂'] },
  '🐢': { name: 'turtle', keywords: ['reptile', '🐢'] },
  '🐍': { name: 'snake', keywords: ['reptile', '🐍'] },
  '🦎': { name: 'lizard', keywords: ['reptile', '🦎'] },
  '🦖': { name: 'T-Rex', keywords: ['dinosaur', 'reptile', '🦖'] },
  '🦕': { name: 'sauropod', keywords: ['dinosaur', 'reptile', '🦕'] },
  '🐙': { name: 'octopus', keywords: ['mollusk', '🐙'] },
  '🦑': { name: 'squid', keywords: ['mollusk', '🦑'] },
  '🦐': { name: 'shrimp', keywords: ['crustacean', '🦐'] },
  '🦞': { name: 'lobster', keywords: ['crustacean', '🦞'] },
  '🦀': { name: 'crab', keywords: ['crustacean', '🦀'] },
  '🐡': { name: 'blowfish', keywords: ['fish', '🐡'] },
  '🐠': { name: 'tropical fish', keywords: ['fish', '🐠'] },
  '🐟': { name: 'fish', keywords: ['🐟'] },
  '🐬': { name: 'dolphin', keywords: ['mammal', 'marine', '🐬'] },
  '🐳': { name: 'spouting whale', keywords: ['mammal', 'marine', '🐳'] },
  '🐋': { name: 'whale', keywords: ['mammal', 'marine', '🐋'] },
  '🦈': { name: 'shark', keywords: ['fish', 'marine', '🦈'] },
  '🐊': { name: 'crocodile', keywords: ['reptile', '🐊'] },
  '🐅': { name: 'tiger', keywords: ['animal', 'cat', '🐅'] },
  '🐆': { name: 'leopard', keywords: ['animal', 'cat', '🐆'] },
  '🦓': { name: 'zebra', keywords: ['animal', 'mammal', '🦓'] },
  '🦍': { name: 'gorilla', keywords: ['animal', 'primate', '🦍'] },
  '🦧': { name: 'orangutan', keywords: ['animal', 'primate', '🦧'] },
  '🐘': { name: 'elephant', keywords: ['animal', 'mammal', '🐘'] },
  '🦛': { name: 'hippopotamus', keywords: ['animal', 'mammal', '🦛'] },
  '🦏': { name: 'rhinoceros', keywords: ['animal', 'mammal', '🦏'] },
  '🐪': { name: 'camel', keywords: ['animal', 'mammal', '🐪'] },
  '🐫': { name: 'two-hump camel', keywords: ['animal', 'mammal', '🐫'] },
  '🦒': { name: 'giraffe', keywords: ['animal', 'mammal', '🦒'] },
  '🦘': { name: 'kangaroo', keywords: ['animal', 'mammal', '🦘'] },
  '🐃': { name: 'water buffalo', keywords: ['animal', 'mammal', '🐃'] },
  '🐂': { name: 'ox', keywords: ['animal', 'mammal', '🐂'] },
  '🐄': { name: 'cow', keywords: ['animal', 'mammal', '🐄'] },
  '🐎': { name: 'horse', keywords: ['animal', 'mammal', '🐎'] },
  '🐖': { name: 'pig', keywords: ['animal', 'mammal', '🐖'] },
  '🐏': { name: 'ram', keywords: ['animal', 'mammal', '🐏'] },
  '🐑': { name: 'ewe', keywords: ['animal', 'mammal', '🐑'] },
  '🦙': { name: 'llama', keywords: ['animal', 'mammal', '🦙'] },
  '🐐': { name: 'goat', keywords: ['animal', 'mammal', '🐐'] },
  '🦌': { name: 'deer', keywords: ['animal', 'mammal', '🦌'] },
  '🐕': { name: 'dog', keywords: ['animal', 'mammal', '🐕'] },
  '🐩': { name: 'poodle', keywords: ['animal', 'mammal', '🐩'] },
  '🦮': { name: 'guide dog', keywords: ['animal', 'mammal', 'disability', '🦮'] },
  '🐕‍🦺': { name: 'service dog', keywords: ['animal', 'mammal', 'disability', '🐕‍🦺'] },
  '🐈': { name: 'cat', keywords: ['animal', 'mammal', '🐈'] },
  '🐓': { name: 'rooster', keywords: ['animal', 'bird', '🐓'] },
  '🦃': { name: 'turkey', keywords: ['animal', 'bird', '🦃'] },
  '🦚': { name: 'peacock', keywords: ['animal', 'bird', '🦚'] },
  '🦜': { name: 'parrot', keywords: ['animal', 'bird', '🦜'] },
  '🦢': { name: 'swan', keywords: ['animal', 'bird', '🦢'] },
  '🦩': { name: 'flamingo', keywords: ['animal', 'bird', '🦩'] },
  '🕊️': { name: 'dove', keywords: ['animal', 'bird', 'peace', '🕊️'] },
  '🐇': { name: 'rabbit', keywords: ['animal', 'mammal', '🐇'] },
  '🦝': { name: 'raccoon', keywords: ['animal', 'mammal', '🦝'] },
  '🦨': { name: 'skunk', keywords: ['animal', 'mammal', '🦨'] },
  '🦡': { name: 'badger', keywords: ['animal', 'mammal', '🦡'] },
  '🦦': { name: 'otter', keywords: ['animal', 'mammal', '🦦'] },
  '🦥': { name: 'sloth', keywords: ['animal', 'mammal', '🦥'] },
  '🐁': { name: 'mouse', keywords: ['animal', 'mammal', '🐁'] },
  '🐀': { name: 'rat', keywords: ['animal', 'mammal', '🐀'] },
  '🐿️': { name: 'chipmunk', keywords: ['animal', 'mammal', '🐿️'] },
  '🦔': { name: 'hedgehog', keywords: ['animal', 'mammal', '🦔'] },
  '🐾': { name: 'paw prints', keywords: ['animal', 'paw', '🐾'] },
  '🐉': { name: 'dragon', keywords: ['mythical', 'fantasy', '🐉'] },
  '🐲': { name: 'dragon face', keywords: ['mythical', 'fantasy', '🐲'] },
  '🌵': { name: 'cactus', keywords: ['plant', 'desert', '🌵'] },
  '🎄': { name: 'christmas tree', keywords: ['plant', 'holiday', '🎄'] },
  '🌲': { name: 'evergreen tree', keywords: ['plant', 'tree', '🌲'] },
  '🌳': { name: 'deciduous tree', keywords: ['plant', 'tree', '🌳'] },
  '🌴': { name: 'palm tree', keywords: ['plant', 'tree', '🌴'] },
  '🌱': { name: 'seedling', keywords: ['plant', 'new', '🌱'] },
  '🌿': { name: 'herb', keywords: ['plant', 'leaf', '🌿'] },
  '☘️': { name: 'shamrock', keywords: ['plant', 'luck', '☘️'] },
  '🍀': { name: 'four leaf clover', keywords: ['plant', 'luck', '🍀'] },
  '🎍': { name: 'pine decoration', keywords: ['plant', 'bamboo', '🎍'] },
  '🎋': { name: 'tanabata tree', keywords: ['plant', 'bamboo', '🎋'] },
  '🍃': { name: 'leaf fluttering in wind', keywords: ['plant', 'leaf', '🍃'] },
  '🍂': { name: 'fallen leaf', keywords: ['plant', 'leaf', 'autumn', '🍂'] },
  '🍁': { name: 'maple leaf', keywords: ['plant', 'leaf', 'canada', '🍁'] },
  '🍄': { name: 'mushroom', keywords: ['plant', 'fungus', '🍄'] },
  '🐚': { name: 'spiral shell', keywords: ['sea', 'shell', '🐚'] },
  '🌾': { name: 'sheaf of rice', keywords: ['plant', 'grain', '🌾'] },
  '💐': { name: 'bouquet', keywords: ['flower', 'plant', '💐'] },
  '🌷': { name: 'tulip', keywords: ['flower', 'plant', '🌷'] },
  '🌹': { name: 'rose', keywords: ['flower', 'plant', 'love', '🌹'] },
  '🥀': { name: 'wilted flower', keywords: ['flower', 'plant', 'sad', '🥀'] },
  '🌺': { name: 'hibiscus', keywords: ['flower', 'plant', '🌺'] },
  '🌸': { name: 'cherry blossom', keywords: ['flower', 'plant', 'japan', '🌸'] },
  '🌼': { name: 'blossom', keywords: ['flower', 'plant', '🌼'] },
  '🌻': { name: 'sunflower', keywords: ['flower', 'plant', '🌻'] },
  '🌞': { name: 'sun with face', keywords: ['weather', 'sun', '🌞'] },
  '🌝': { name: 'full moon face', keywords: ['weather', 'moon', '🌝'] },
  '🌛': { name: 'first quarter moon face', keywords: ['weather', 'moon', '🌛'] },
  '🌜': { name: 'last quarter moon face', keywords: ['weather', 'moon', '🌜'] },
  '🌚': { name: 'new moon face', keywords: ['weather', 'moon', '🌚'] },
  '🌕': { name: 'full moon', keywords: ['weather', 'moon', '🌕'] },
  '🌖': { name: 'waning gibbous moon', keywords: ['weather', 'moon', '🌖'] },
  '🌗': { name: 'last quarter moon', keywords: ['weather', 'moon', '🌗'] },
  '🌘': { name: 'waning crescent moon', keywords: ['weather', 'moon', '🌘'] },
  '🌑': { name: 'new moon', keywords: ['weather', 'moon', '🌑'] },
  '🌒': { name: 'waxing crescent moon', keywords: ['weather', 'moon', '🌒'] },
  '🌓': { name: 'first quarter moon', keywords: ['weather', 'moon', '🌓'] },
  '🌔': { name: 'waxing gibbous moon', keywords: ['weather', 'moon', '🌔'] },
  '🌙': { name: 'crescent moon', keywords: ['weather', 'moon', '🌙'] },
  '🌎': { name: 'globe showing americas', keywords: ['world', 'earth', '🌎'] },
  '🌍': { name: 'globe showing europe-africa', keywords: ['world', 'earth', '🌍'] },
  '🌏': { name: 'globe showing asia-australia', keywords: ['world', 'earth', '🌏'] },
  '🪐': { name: 'ringed planet', keywords: ['space', 'saturn', '🪐'] },
  '💫': { name: 'dizzy', keywords: ['star', 'space', '💫'] },
  '⭐': { name: 'star', keywords: ['space', '⭐'] },
  '🌟': { name: 'glowing star', keywords: ['space', 'star', '🌟'] },
  '✨': { name: 'sparkles', keywords: ['star', 'magic', '✨'] },
  '⚡': { name: 'high voltage', keywords: ['lightning', 'electricity', '⚡'] },
  '☄️': { name: 'comet', keywords: ['space', '☄️'] },
  '💥': { name: 'collision', keywords: ['boom', 'explode', '💥'] },
  '🍎': { name: 'red apple', keywords: ['fruit', 'teacher', 'red', 'apple'] },
  '🍊': { name: 'tangerine', keywords: ['orange', 'fruit', 'citrus', 'tangerine'] },
  '🍋': { name: 'lemon', keywords: ['fruit', 'citrus', 'lemon'] },
  '🍌': { name: 'banana', keywords: ['fruit', 'yellow', 'banana'] },
  '🍉': { name: 'watermelon', keywords: ['fruit', 'summer', 'watermelon'] },
  '🍇': { name: 'grapes', keywords: ['fruit', 'wine', 'grapes'] },
  '🍓': { name: 'strawberry', keywords: ['fruit', 'berry', 'strawberry'] },
  '🫐': { name: 'blueberries', keywords: ['fruit', 'berry', 'blueberries'] },
  '🍈': { name: 'melon', keywords: ['fruit', 'honeydew', 'cantaloupe', 'melon'] },
  '🍒': { name: 'cherries', keywords: ['fruit', 'cherry', 'cherries'] },
  '🍑': { name: 'peach', keywords: ['fruit', 'pit', 'peach'] },
  '🥭': { name: 'mango', keywords: ['fruit', 'tropical', 'mango'] },
  '🍍': { name: 'pineapple', keywords: ['fruit', 'tropical', 'pineapple'] },
  '🥥': { name: 'coconut', keywords: ['fruit', 'tropical', 'coconut'] },
  '🥝': { name: 'kiwi fruit', keywords: ['fruit', 'tropical', 'kiwi'] },
  '🍅': { name: 'tomato', keywords: ['fruit', 'vegetable', 'tomato'] },
  '🍆': { name: 'eggplant', keywords: ['vegetable', 'aubergine', 'eggplant'] },
  '🥑': { name: 'avocado', keywords: ['fruit', 'vegetable', 'avocado'] },
  '🥦': { name: 'broccoli', keywords: ['vegetable', 'floret', 'broccoli'] },
  '🥬': { name: 'leafy green', keywords: ['vegetable', 'lettuce', 'cabbage', 'kale', 'spinach', 'leafy green'] },
  '🥒': { name: 'cucumber', keywords: ['vegetable', 'pickle', 'cucumber'] },
  '🌶️': { name: 'hot pepper', keywords: ['vegetable', 'spicy', 'chili', 'hot pepper'] },
  '🫑': { name: 'bell pepper', keywords: ['vegetable', 'pepper', 'bell pepper'] },
  '🌽': { name: 'ear of corn', keywords: ['vegetable', 'maize', 'corn'] },
  '🥕': { name: 'carrot', keywords: ['vegetable', 'orange', 'carrot'] },
  '🫒': { name: 'olive', keywords: ['fruit', 'mediterranean', 'olive'] },
  '🧄': { name: 'garlic', keywords: ['vegetable', 'flavoring', 'garlic'] },
  '🧅': { name: 'onion', keywords: ['vegetable', 'flavoring', 'onion'] },
  '🥔': { name: 'potato', keywords: ['vegetable', 'tuber', 'potato'] },
  '🍠': { name: 'roasted sweet potato', keywords: ['vegetable', 'tuber', 'sweet potato'] },
  '🥐': { name: 'croissant', keywords: ['bread', 'pastry', 'french', 'croissant'] },
  '🥯': { name: 'bagel', keywords: ['bread', 'schmear', 'bagel'] },
  '🍞': { name: 'bread', keywords: ['toast', 'loaf', 'bread'] },
  '🥖': { name: 'baguette bread', keywords: ['bread', 'french', 'baguette'] },
  '🥨': { name: 'pretzel', keywords: ['bread', 'twisted', 'pretzel'] },
  '🧀': { name: 'cheese wedge', keywords: ['dairy', 'cheese'] },
  '🥚': { name: 'egg', keywords: ['dairy', 'breakfast', 'egg'] },
  '🍳': { name: 'cooking', keywords: ['egg', 'breakfast', 'frying pan', 'cooking'] },
  '🧈': { name: 'butter', keywords: ['dairy', 'margarine', 'butter'] },
  '🥞': { name: 'pancakes', keywords: ['breakfast', 'flapjacks', 'hotcakes', 'pancakes'] },
  '🧇': { name: 'waffle', keywords: ['breakfast', 'belgian', 'waffle'] },
  '🥓': { name: 'bacon', keywords: ['pork', 'breakfast', 'bacon'] },
  '🥩': { name: 'cut of meat', keywords: ['beef', 'pork', 'steak', 'meat'] },
  '🍗': { name: 'poultry leg', keywords: ['chicken', 'turkey', 'drumstick', 'poultry'] },
  '🍖': { name: 'meat on bone', keywords: ['pork', 'beef', 'ribs', 'meat'] },
  '🌭': { name: 'hot dog', keywords: ['sausage', 'bun', 'frankfurter', 'hot dog'] },
  '🍔': { name: 'hamburger', keywords: ['beef', 'burger', 'cheeseburger', 'hamburger'] },
  '🍟': { name: 'french fries', keywords: ['potato', 'chips', 'fries'] },
  '🍕': { name: 'pizza', keywords: ['cheese', 'pepperoni', 'pie', 'pizza'] },
  '🫓': { name: 'flatbread', keywords: ['naan', 'pita', 'roti', 'flatbread'] },
  '🥪': { name: 'sandwich', keywords: ['bread', 'lunch', 'sandwich'] },
  '🥙': { name: 'stuffed flatbread', keywords: ['pita', 'gyro', 'kebab', 'falafel', 'stuffed flatbread'] },
  '🧆': { name: 'falafel', keywords: ['chickpea', 'middle eastern', 'falafel'] },
  '🌮': { name: 'taco', keywords: ['mexican', 'shell', 'taco'] },
  '🌯': { name: 'burrito', keywords: ['mexican', 'wrap', 'burrito'] },
  '🫔': { name: 'tamale', keywords: ['mexican', 'masa', 'tamale'] },
  '🥗': { name: 'green salad', keywords: ['vegetable', 'healthy', 'salad'] },
  '🥘': { name: 'shallow pan of food', keywords: ['paella', 'spanish', 'casserole', 'pan'] },
  '🫕': { name: 'fondue', keywords: ['cheese', 'chocolate', 'swiss', 'fondue'] },
  '🍝': { name: 'spaghetti', keywords: ['pasta', 'italian', 'noodles', 'spaghetti'] },
  '🍜': { name: 'steaming bowl', keywords: ['ramen', 'noodles', 'japanese', 'soup', 'bowl'] },
  '🍲': { name: 'pot of food', keywords: ['soup', 'stew', 'casserole', 'pot'] },
  '🍛': { name: 'curry rice', keywords: ['indian', 'japanese', 'thai', 'curry'] },
  '🍣': { name: 'sushi', keywords: ['japanese', 'fish', 'rice', 'sushi'] },
  '🍱': { name: 'bento box', keywords: ['japanese', 'lunchbox', 'bento'] },
  '🥟': { name: 'dumpling', keywords: ['chinese', 'potsticker', 'gyoza', 'dumpling'] },
  '🦪': { name: 'oyster', keywords: ['seafood', 'shellfish', 'oyster'] },
  '🍤': { name: 'fried shrimp', keywords: ['seafood', 'tempura', 'prawn', 'shrimp'] },
  '🍙': { name: 'rice ball', keywords: ['japanese', 'onigiri', 'rice'] },
  '🍚': { name: 'cooked rice', keywords: ['steamed', 'white', 'rice'] },
  '🍘': { name: 'rice cracker', keywords: ['japanese', 'senbei', 'cracker'] },
  '🍥': { name: 'fish cake with swirl', keywords: ['japanese', 'narutomaki', 'kamaboko', 'fish cake'] },
  '🥠': { name: 'fortune cookie', keywords: ['chinese', 'prophecy', 'cookie'] },
  '🥮': { name: 'moon cake', keywords: ['chinese', 'festival', 'pastry', 'moon cake'] },
  '🍢': { name: 'oden', keywords: ['japanese', 'skewer', 'broth', 'oden'] },
  '🍡': { name: 'dango', keywords: ['japanese', 'dessert', 'skewer', 'dango'] },
  '🍧': { name: 'shaved ice', keywords: ['dessert', 'hawaiian', 'kakigori', 'ice'] },
  '🍨': { name: 'ice cream', keywords: ['dessert', 'sundae', 'ice cream'] },
  '🍦': { name: 'soft ice cream', keywords: ['dessert', 'cone', 'soft serve', 'ice cream'] },
  '🥧': { name: 'pie', keywords: ['dessert', 'pastry', 'filling', 'pie'] },
  '🧁': { name: 'cupcake', keywords: ['dessert', 'cake', 'icing', 'cupcake'] },
  '🍰': { name: 'shortcake', keywords: ['dessert', 'cake', 'strawberry', 'shortcake'] },
  '🎂': { name: 'birthday cake', keywords: ['dessert', 'celebration', 'party', 'cake'] },
  '🍮': { name: 'custard', keywords: ['dessert', 'flan', 'pudding', 'custard'] },
  '🍭': { name: 'lollipop', keywords: ['dessert', 'candy', 'sucker', 'lollipop'] },
  '🍬': { name: 'candy', keywords: ['dessert', 'sweet', 'gummy', 'candy'] },
  '🍫': { name: 'chocolate bar', keywords: ['dessert', 'candy', 'cocoa', 'chocolate'] },
  '🍿': { name: 'popcorn', keywords: ['snack', 'movie', 'corn', 'popcorn'] },
  '🍩': { name: 'doughnut', keywords: ['dessert', 'donut', 'sprinkles', 'doughnut'] },
  '🍪': { name: 'cookie', keywords: ['dessert', 'chocolate chip', 'biscuit', 'cookie'] },
  '🌰': { name: 'chestnut', keywords: ['nut', 'roasting', 'christmas', 'chestnut'] },
  '🥜': { name: 'peanuts', keywords: ['nut', 'legume', 'peanut'] },
  '🍯': { name: 'honey pot', keywords: ['sweetener', 'bee', 'honey'] },
  '🥛': { name: 'glass of milk', keywords: ['drink', 'dairy', 'calcium', 'milk'] },
  '🍼': { name: 'baby bottle', keywords: ['drink', 'milk', 'infant', 'baby'] },
  '☕': { name: 'hot beverage', keywords: ['drink', 'coffee', 'tea', 'espresso', 'beverage'] },
  '🫖': { name: 'teapot', keywords: ['drink', 'tea', 'kettle', 'teapot'] },
  '🍵': { name: 'teacup without handle', keywords: ['drink', 'tea', 'green tea', 'matcha', 'teacup'] },
  '🧃': { name: 'juice box', keywords: ['drink', 'fruit', 'carton', 'juice'] },
  '🥤': { name: 'cup with straw', keywords: ['drink', 'soda', 'juice', 'takeaway', 'cup'] },
  '🧋': { name: 'bubble tea', keywords: ['drink', 'boba', 'pearl milk tea', 'bubble tea'] },
  '🍶': { name: 'sake', keywords: ['drink', 'japanese', 'rice wine', 'sake'] },
  '🍺': { name: 'beer mug', keywords: ['drink', 'ale', 'lager', 'pint', 'beer'] },
  '🍻': { name: 'clinking beer mugs', keywords: ['drink', 'cheers', 'toast', 'beer'] },
  '🥂': { name: 'clinking glasses', keywords: ['drink', 'cheers', 'toast', 'champagne', 'prosecco'] },
  '🍷': { name: 'wine glass', keywords: ['drink', 'red', 'white', 'cabernet', 'merlot', 'wine'] },
  '🥃': { name: 'tumbler glass', keywords: ['drink', 'whiskey', 'bourbon', 'scotch', 'glass'] },
  '🍸': { name: 'cocktail glass', keywords: ['drink', 'martini', 'manhattan', 'cocktail'] },
  '🍹': { name: 'tropical drink', keywords: ['drink', 'vacation', 'pineapple', 'cocktail'] },
  '🧉': { name: 'mate', keywords: ['drink', 'south american', 'yerba', 'mate'] },
  '🍾': { name: 'bottle with popping cork', keywords: ['drink', 'champagne', 'prosecco', 'celebration', 'bottle'] },
  '🧊': { name: 'ice cube', keywords: ['frozen', 'water', 'cold', 'ice'] },
  '🥄': { name: 'spoon', keywords: ['cutlery', 'utensil', 'spoon'] },
  '🍴': { name: 'fork and knife', keywords: ['cutlery', 'utensil', 'dining', 'fork', 'knife'] },
  '🍽️': { name: 'fork and knife with plate', keywords: ['cutlery', 'utensil', 'dining', 'eating', 'plate'] },
  '🥣': { name: 'bowl with spoon', keywords: ['cutlery', 'utensil', 'cereal', 'soup', 'bowl'] },
  '🥡': { name: 'takeout box', keywords: ['food', 'chinese', 'oyster pail', 'takeout'] },
  '🥢': { name: 'chopsticks', keywords: ['cutlery', 'utensil', 'asian', 'chopsticks'] },
  '🧂': { name: 'salt', keywords: ['condiment', 'shaker', 'sodium', 'salt'] },
  '⚽': { name: 'soccer ball', keywords: ['sport', 'football', 'soccer'] },
  '🏀': { name: 'basketball', keywords: ['sport', 'hoops', 'basketball'] },
  '🏈': { name: 'american football', keywords: ['sport', 'nfl', 'gridiron', 'football'] },
  '⚾': { name: 'baseball', keywords: ['sport', 'mlb', 'diamond', 'baseball'] },
  '🥎': { name: 'softball', keywords: ['sport', 'underhand', 'softball'] },
  '🎾': { name: 'tennis', keywords: ['sport', 'racket', 'wimbledon', 'tennis'] },
  '🏐': { name: 'volleyball', keywords: ['sport', 'beach', 'net', 'volleyball'] },
  '🏉': { name: 'rugby football', keywords: ['sport', 'scrum', 'oval', 'rugby'] },
  '🥏': { name: 'flying disc', keywords: ['sport', 'frisbee', 'ultimate', 'disc'] },
  '🎱': { name: 'pool 8 ball', keywords: ['game', 'billiards', 'pool', 'eight ball'] },
  '🪀': { name: 'yo-yo', keywords: ['toy', 'game', 'string', 'yo-yo'] },
  '🏓': { name: 'ping pong', keywords: ['game', 'table tennis', 'paddle', 'ping pong'] },
  '🏸': { name: 'badminton', keywords: ['sport', 'shuttlecock', 'racket', 'badminton'] },
  '🏒': { name: 'ice hockey', keywords: ['sport', 'puck', 'stick', 'hockey'] },
  '🏑': { name: 'field hockey', keywords: ['sport', 'stick', 'ball', 'hockey'] },
  '🥍': { name: 'lacrosse', keywords: ['sport', 'stick', 'net', 'lacrosse'] },
  '🏏': { name: 'cricket game', keywords: ['sport', 'bat', 'ball', 'wicket', 'cricket'] },
  '🪃': { name: 'boomerang', keywords: ['toy', 'australia', 'throwing', 'boomerang'] },
  '🥅': { name: 'goal net', keywords: ['sport', 'score', 'net', 'goal'] },
  '⛳': { name: 'flag in hole', keywords: ['sport', 'golf', 'green', 'hole'] },
  '🪁': { name: 'kite', keywords: ['toy', 'wind', 'fly', 'kite'] },
  '🏹': { name: 'bow and arrow', keywords: ['weapon', 'archery', 'target', 'arrow'] },
  '🎣': { name: 'fishing pole', keywords: ['hobby', 'fish', 'reel', 'fishing'] },
  '🤿': { name: 'diving mask', keywords: ['activity', 'scuba', 'snorkel', 'diving'] },
  '🥊': { name: 'boxing glove', keywords: ['sport', 'fight', 'punch', 'boxing'] },
  '🥋': { name: 'martial arts uniform', keywords: ['sport', 'judo', 'karate', 'taekwondo', 'martial arts'] },
  '🎽': { name: 'running shirt', keywords: ['sport', 'marathon', 'race', 'running'] },
  '🛹': { name: 'skateboard', keywords: ['sport', 'deck', 'wheels', 'skateboarding'] },
  '🛼': { name: 'roller skate', keywords: ['sport', 'wheels', 'retro', 'roller skating'] },
  '🛷': { name: 'sled', keywords: ['activity', 'snow', 'winter', 'sledding'] },
  '⛸️': { name: 'ice skate', keywords: ['sport', 'winter', 'figure skating', 'ice skating'] },
  '🥌': { name: 'curling stone', keywords: ['sport', 'winter', 'ice', 'curling'] },
  '🎿': { name: 'skis', keywords: ['sport', 'winter', 'snow', 'skiing'] },
  '⛷️': { name: 'skier', keywords: ['sport', 'winter', 'snow', 'skiing'] },
  '🏂': { name: 'snowboarder', keywords: ['sport', 'winter', 'snow', 'snowboarding'] },
  '🪂': { name: 'parachute', keywords: ['activity', 'skydiving', 'jump', 'parachute'] },
  '🏋️‍♀️': { name: 'woman lifting weights', keywords: ['sport', 'gym', 'fitness', 'woman', 'weightlifting'] },
  '🏋️': { name: 'person lifting weights', keywords: ['sport', 'gym', 'fitness', 'weightlifting'] },
  '🤼‍♀️': { name: 'women wrestling', keywords: ['sport', 'wwe', 'grappling', 'women', 'wrestling'] },
  '🤼': { name: 'people wrestling', keywords: ['sport', 'wwe', 'grappling', 'wrestling'] },
  '🤸‍♀️': { name: 'woman cartwheeling', keywords: ['sport', 'gymnastics', 'flip', 'woman', 'cartwheel'] },
  '🤸': { name: 'person cartwheeling', keywords: ['sport', 'gymnastics', 'flip', 'cartwheel'] },
  '⛹️‍♀️': { name: 'woman bouncing ball', keywords: ['sport', 'basketball', 'dribble', 'woman'] },
  '⛹️': { name: 'person bouncing ball', keywords: ['sport', 'basketball', 'dribble'] },
  '🤺': { name: 'person fencing', keywords: ['sport', 'sword', 'epee', 'foil', 'sabre', 'fencing'] },
  '🤾‍♀️': { name: 'woman playing handball', keywords: ['sport', 'net', 'ball', 'woman', 'handball'] },
  '🤾': { name: 'person playing handball', keywords: ['sport', 'net', 'ball', 'handball'] },
  '🏌️‍♀️': { name: 'woman golfing', keywords: ['sport', 'caddy', 'swing', 'woman', 'golfing'] },
  '🏌️': { name: 'person golfing', keywords: ['sport', 'caddy', 'swing', 'golfing'] },
  '🏇': { name: 'horse racing', keywords: ['sport', 'jockey', 'derby', 'horse'] },
  '🧘‍♀️': { name: 'woman in lotus position', keywords: ['activity', 'meditation', 'zen', 'woman', 'yoga'] },
  '🧘': { name: 'person in lotus position', keywords: ['activity', 'meditation', 'zen', 'yoga'] },
  '🏄‍♀️': { name: 'woman surfing', keywords: ['sport', 'beach', 'wave', 'woman', 'surfing'] },
  '🏄': { name: 'person surfing', keywords: ['sport', 'beach', 'wave', 'surfing'] },
  '🏊‍♀️': { name: 'woman swimming', keywords: ['sport', 'pool', 'water', 'woman', 'swimming'] },
  '🏊': { name: 'person swimming', keywords: ['sport', 'pool', 'water', 'swimming'] },
  '🤽‍♀️': { name: 'woman playing water polo', keywords: ['sport', 'pool', 'water', 'woman', 'water polo'] },
  '🤽': { name: 'person playing water polo', keywords: ['sport', 'pool', 'water', 'water polo'] },
  '🚣‍♀️': { name: 'woman rowing boat', keywords: ['activity', 'water', 'oar', 'woman', 'rowing'] },
  '🚣': { name: 'person rowing boat', keywords: ['activity', 'water', 'oar', 'rowing'] },
  '🧗‍♀️': { name: 'woman climbing', keywords: ['activity', 'bouldering', 'rock climbing', 'woman'] },
  '🧗': { name: 'person climbing', keywords: ['activity', 'bouldering', 'rock climbing'] },
  '🚵‍♀️': { name: 'woman mountain biking', keywords: ['sport', 'bicycle', 'trail', 'woman', 'mountain biking'] },
  '🚵': { name: 'person mountain biking', keywords: ['sport', 'bicycle', 'trail', 'mountain biking'] },
  '🚴‍♀️': { name: 'woman biking', keywords: ['sport', 'bicycle', 'commute', 'woman', 'biking'] },
  '🚴': { name: 'person biking', keywords: ['sport', 'bicycle', 'commute', 'biking'] },
  '🏆': { name: 'trophy', keywords: ['award', 'prize', 'winner', 'trophy'] },
  '🥇': { name: '1st place medal', keywords: ['award', 'gold', 'winner', 'first'] },
  '🥈': { name: '2nd place medal', keywords: ['award', 'silver', 'second'] },
  '🥉': { name: '3rd place medal', keywords: ['award', 'bronze', 'third'] },
  '🏅': { name: 'sports medal', keywords: ['award', 'prize', 'medal'] },
  '🎖️': { name: 'military medal', keywords: ['award', 'military', 'honor', 'medal'] },
  '🏵️': { name: 'rosette', keywords: ['award', 'prize', 'ribbon', 'rosette'] },
  '🎗️': { name: 'reminder ribbon', keywords: ['awareness', 'support', 'cause', 'ribbon'] },
  '🎫': { name: 'ticket', keywords: ['event', 'admission', 'concert', 'movie', 'ticket'] },
  '🎟️': { name: 'admission tickets', keywords: ['event', 'admission', 'concert', 'movie', 'ticket'] },
  '🎪': { name: 'circus tent', keywords: ['event', 'carnival', 'big top', 'circus'] },
  '🤹': { name: 'person juggling', keywords: ['activity', 'multitask', 'skill', 'juggling'] },
  '🤹‍♀️': { name: 'woman juggling', keywords: ['activity', 'multitask', 'skill', 'woman', 'juggling'] },
  '🎭': { name: 'performing arts', keywords: ['activity', 'theater', 'drama', 'masks'] },
  '🩰': { name: 'ballet shoes', keywords: ['activity', 'dance', 'pointe', 'ballet'] },
  '🎨': { name: 'artist palette', keywords: ['hobby', 'painting', 'colors', 'art'] },
  '🎬': { name: 'clapper board', keywords: ['entertainment', 'movie', 'film', 'video'] },
  '🎤': { name: 'microphone', keywords: ['entertainment', 'sing', 'karaoke', 'speak'] },
  '🎧': { name: 'headphone', keywords: ['audio', 'music', 'listen', 'podcast'] },
  '🎼': { name: 'musical score', keywords: ['music', 'notes', 'sheet music', 'score'] },
  '🎵': { name: 'musical note', keywords: ['music', 'sound', 'melody', 'note'] },
  '🎶': { name: 'musical notes', keywords: ['music', 'sound', 'melody', 'notes'] },
  '🥁': { name: 'drum', keywords: ['music', 'percussion', 'beat', 'drum'] },
  '🪘': { name: 'long drum', keywords: ['music', 'percussion', 'djembe', 'conga'] },
  '🎹': { name: 'musical keyboard', keywords: ['music', 'instrument', 'piano', 'keyboard'] },
  '🎻': { name: 'violin', keywords: ['music', 'instrument', 'strings', 'orchestra'] },
  '🎺': { name: 'trumpet', keywords: ['music', 'instrument', 'brass', 'jazz'] },
  '🎸': { name: 'guitar', keywords: ['music', 'instrument', 'strings', 'rock'] },
  '🪕': { name: 'banjo', keywords: ['music', 'instrument', 'strings', 'folk'] },
  '🎷': { name: 'saxophone', keywords: ['music', 'instrument', 'brass', 'jazz'] },
  '🎯': { name: 'direct hit', keywords: ['game', 'target', 'bullseye', 'darts'] },
  '🎳': { name: 'bowling', keywords: ['game', 'pins', 'strike', 'alley'] },
  '🎮': { name: 'video game', keywords: ['game', 'controller', 'console', 'gaming'] },
  '🎰': { name: 'slot machine', keywords: ['game', 'gambling', 'casino', 'jackpot'] },
  // ... and so on for all emojis
}; 