export const EMOJI_DATA: { [key: string]: { name: string; keywords: string[] } } = {
  '😀': { name: 'grinning face', keywords: ['face', 'smile', 'happy', 'joy', '😀'] },
  '😃': { name: 'grinning face with big eyes', keywords: ['face', 'happy', 'joy', 'haha', '😃'] },
  '😄': { name: 'grinning face with smiling eyes', keywords: ['face', 'happy', 'joy', 'funny', 'haha', 'laugh', 'like', '😄'] },
  '😁': { name: 'beaming face with smiling eyes', keywords: ['face', 'happy', 'smile', 'joy', '😁'] },
  '😆': { name: 'grinning squinting face', keywords: ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'laugh', '😆'] },
  '😅': { name: 'grinning face with sweat', keywords: ['face', 'hot', 'happy', 'laugh', 'sweat', 'smile', 'relief', '😅'] },
  '😂': { name: 'face with tears of joy', keywords: ['face', 'cry', 'tears', 'weep', 'happy', 'haha', 'joy', '😂'] },
  '🤣': { name: 'rolling on the floor laughing', keywords: ['face', 'rolling', 'lol', 'laughing', 'haha', '🤣'] },
  '😊': { name: 'smiling face with smiling eyes', keywords: ['face', 'smile', 'happy', 'flushed', 'crush', 'good', '😊'] },
  '😇': { name: 'smiling face with halo', keywords: ['face', 'angel', 'heaven', 'halo', '😇'] },
  '🙂': { name: 'slightly smiling face', keywords: ['face', 'smile', '🙂'] },
  '🙃': { name: 'upside-down face', keywords: ['face', 'silly', 'sarcasm', '🙃'] },
  '😉': { name: 'winking face', keywords: ['face', 'happy', 'mischievous', 'secret', 'wink', '😉'] },
  '😌': { name: 'relieved face', keywords: ['face', 'relaxed', 'phew', 'massage', 'happiness', '😌'] },
  '😍': { name: 'smiling face with heart-eyes', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart', '😍'] },
  '🥰': { name: 'smiling face with hearts', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'hearts', '🥰'] },
  '😘': { name: 'face blowing a kiss', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss', '😘'] },
  '😗': { name: 'kissing face', keywords: ['love', 'like', 'face', '3', 'valentines', 'infatuation', 'kiss', '😗'] },
  '😙': { name: 'kissing face with smiling eyes', keywords: ['face', 'affection', 'valentines', 'infatuation', 'kiss', '😙'] },
  '😚': { name: 'kissing face with closed eyes', keywords: ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss', '😚'] },
  '😋': { name: 'face savoring food', keywords: ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', '😋'] },
  '😛': { name: 'face with tongue', keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'tongue', '😛'] },
  '😝': { name: 'squinting face with tongue', keywords: ['face', 'prank', 'playful', 'mischievous', 'tongue', '😝'] },
  '😜': { name: 'winking face with tongue', keywords: ['face', 'prank', 'childish', 'playful', 'mischievous', 'wink', 'tongue', '😜'] },
  '🤪': { name: 'zany face', keywords: ['face', 'goofy', 'crazy', '🤪'] },
  '🤨': { name: 'face with raised eyebrow', keywords: ['face', 'skeptical', 'suspicious', '🤨'] },
  '🧐': { name: 'face with monocle', keywords: ['face', 'stuffy', 'wealthy', '🧐'] },
  '🤓': { name: "nerd face", keywords: ["face", "nerdy", "geek", "dork", "🤓"] },
  '😎': { name: "smiling face with sunglasses", keywords: ["face", "cool", "sunglasses", "😎"] },
  '🤩': { name: "star-struck", keywords: ["face", "star", "eyes", "grinning", "🤩"] },
  '🥳': { name: "partying face", keywords: ["face", "party", "hat", "celebration", "🥳"] },
  '😏': { name: "smirking face", keywords: ["face", "smirk", "smug", "😏"] },
  '😒': { name: "unamused face", keywords: ["face", "unamused", "annoyed", "😒"] },
  '😞': { name: "disappointed face", keywords: ["face", "sad", "disappointed", "😞"] },
  '😔': { name: "pensive face", keywords: ["face", "sad", "pensive", "😔"] },
  '😟': { name: "worried face", keywords: ["face", "worried", "nervous", "😟"] },
  '😕': { name: "confused face", keywords: ["face", "confused", "uncertain", "😕"] },
  '🙁': { name: "slightly frowning face", keywords: ["face", "sad", "frowning", "🙁"] },
  '☹️': { name: "frowning face", keywords: ["face", "sad", "frowning", "☹️"] },
  '😣': { name: "persevering face", keywords: ["face", "struggling", "persevering", "😣"] },
  '😖': { name: "confounded face", keywords: ["face", "confounded", "struggling", "😖"] },
  '😫': { name: "tired face", keywords: ["face", "tired", "exhausted", "😫"] },
  '😩': { name: "weary face", keywords: ["face", "weary", "exhausted", "😩"] },
  '🥺': { name: "pleading face", keywords: ["face", "pleading", "begging", "🥺"] },
  '😢': { name: "crying face", keywords: ["face", "sad", "crying", "😢"] },
  '😭': { name: "loudly crying face", keywords: ["face", "sad", "crying", "😭"] },
  '😤': { name: "face with steam from nose", keywords: ["face", "angry", "triumph", "😤"] },
  '😠': { name: "angry face", keywords: ["face", "angry", "mad", "😠"] },
  '😡': { name: "pouting face", keywords: ["face", "angry", "pouting", "😡"] },
  '🤬': { name: "face with symbols on mouth", keywords: ["face", "swearing", "cursing", "🤬"] },
  '🤯': { name: "exploding head", keywords: ["face", "shocked", "mind blown", "🤯"] },
  '😳': { name: "flushed face", keywords: ["face", "flushed", "blushing", "😳"] },
  '🥵': { name: "hot face", keywords: ["face", "hot", "sweating", "🥵"] },
  '🥶': { name: "cold face", keywords: ["face", "cold", "freezing", "🥶"] },
  '😱': { name: "face screaming in fear", keywords: ["face", "scream", "fear", "😱"] },
  '😨': { name: "fearful face", keywords: ["face", "fear", "scared", "😨"] },
  '😰': { name: "anxious face with sweat", keywords: ["face", "anxious", "nervous", "😰"] },
  '😥': { name: "sad but relieved face", keywords: ["face", "sad", "relieved", "😥"] },
  '😓': { name: "downcast face with sweat", keywords: ["face", "sad", "sweat", "😓"] },
  '🤗': { name: "hugging face", keywords: ["face", "hug", "🤗"] },
  '🤔': { name: "thinking face", keywords: ["face", "thinking", "🤔"] },
  '🤭': { name: "face with hand over mouth", keywords: ["face", "oops", "giggle", "🤭"] },
  '🤫': { name: "shushing face", keywords: ["face", "shush", "quiet", "🤫"] },
  '🤥': { name: "lying face", keywords: ["face", "lie", "pinocchio", "🤥"] },
  '😶': { name: "face without mouth", keywords: ["face", "silent", "quiet", "😶"] },
  '😐': { name: "neutral face", keywords: ["face", "neutral", "😐"] },
  '😑': { name: "expressionless face", keywords: ["face", "expressionless", "😑"] },
  '😬': { name: "grimacing face", keywords: ["face", "grimace", "awkward", "😬"] },
  '🙄': { name: "face with rolling eyes", keywords: ["face", "rolling eyes", "annoyed", "🙄"] },
  '😯': { name: "hushed face", keywords: ["face", "hushed", "surprised", "😯"] },
  '😦': { name: "frowning face with open mouth", keywords: ["face", "frowning", "surprised", "😦"] },
  '😧': { name: "anguished face", keywords: ["face", "anguished", "pained", "😧"] },
  '😮': { name: "face with open mouth", keywords: ["face", "surprised", "shocked", "😮"] },
  '😲': { name: "astonished face", keywords: ["face", "astonished", "shocked", "😲"] },
  '🥱': { name: "yawning face", keywords: ["face", "yawn", "tired", "🥱"] },
  '😴': { name: "sleeping face", keywords: ["face", "sleep", "zzz", "😴"] },
  '🤤': { name: "drooling face", keywords: ["face", "drool", "🤤"] },
  '😪': { name: "sleepy face", keywords: ["face", "sleepy", "tired", "😪"] },
  '😵': { name: "dizzy face", keywords: ["face", "dizzy", "😵"] },
  '🤐': { name: "zipper-mouth face", keywords: ["face", "zip", "secret", "🤐"] },
  '🥴': { name: "woozy face", keywords: ["face", "woozy", "dizzy", "🥴"] },
  '🤢': { name: "nauseated face", keywords: ["face", "nauseous", "sick", "🤢"] },
  '🤮': { name: "face vomiting", keywords: ["face", "vomit", "sick", "🤮"] },
  '🤧': { name: "sneezing face", keywords: ["face", "sneeze", "sick", "🤧"] },
  '😷': { name: "face with medical mask", keywords: ["face", "mask", "sick", "😷"] },
  '🤒': { name: "face with thermometer", keywords: ["face", "thermometer", "sick", "🤒"] },
  '🤕': { name: "face with head-bandage", keywords: ["face", "bandage", "injured", "🤕"] },
  '🤑': { name: "money-mouth face", keywords: ["face", "money", "rich", "🤑"] },
  '🤠': { name: "cowboy hat face", keywords: ["face", "cowboy", "hat", "🤠"] },
  '😈': { name: 'smiling face with horns', keywords: ['face', 'devil', 'evil', '😈'] },
  '👿': { name: 'angry face with horns', keywords: ['face', 'devil', 'evil', '👿'] },
  '👹': { name: 'ogre', keywords: ['monster', 'fantasy', '👹'] },
  '👺': { name: 'goblin', keywords: ['monster', 'fantasy', '👺'] },
  '🤡': { name: 'clown face', keywords: ['face', 'clown', 'circus', '🤡'] },
  '💩': { name: 'pile of poo', keywords: ['poop', 'dung', '💩'] },
  '👻': { name: 'ghost', keywords: ['halloween', 'spooky', '👻'] },
  '💀': { name: 'skull', keywords: ['death', 'skeleton', '💀'] },
  '☠️': { name: 'skull and crossbones', keywords: ['death', 'danger', '☠️'] },
  '👽': { name: 'alien', keywords: ['extraterrestrial', 'ufo', '👽'] },
  '👾': { name: 'alien monster', keywords: ['game', 'retro', '👾'] },
  '🤖': { name: 'robot', keywords: ['android', 'cyborg', '🤖'] },
  '🎃': { name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin', '🎃'] },
  '😺': { name: 'grinning cat', keywords: ['cat', 'animal', '😺'] },
  '😸': { name: 'grinning cat with smiling eyes', keywords: ['cat', 'animal', '😸'] },
  '😹': { name: 'cat with tears of joy', keywords: ['cat', 'animal', '😹'] },
  '😻': { name: 'smiling cat with heart-eyes', keywords: ['cat', 'animal', '😻'] },
  '😼': { name: 'cat with wry smile', keywords: ['cat', 'animal', '😼'] },
  '😽': { name: 'kissing cat', keywords: ['cat', 'animal', '😽'] },
  '🙀': { name: 'weary cat', keywords: ['cat', 'animal', '🙀'] },
  '😿': { name: 'crying cat', keywords: ['cat', 'animal', '😿'] },
  '😾': { name: 'pouting cat', keywords: ['cat', 'animal', '😾'] },
  '👋': { name: 'waving hand', keywords: ['wave', 'hello', 'goodbye', '👋'] },
  '🤚': { name: 'raised back of hand', keywords: ['hand', 'raised', '🤚'] },
  '🖐️': { name: 'hand with fingers splayed', keywords: ['hand', 'fingers', 'splayed', '🖐️'] },
  '✋': { name: 'raised hand', keywords: ['hand', 'raised', '✋'] },
  '🖖': { name: 'vulcan salute', keywords: ['hand', 'vulcan', 'spock', '🖖'] },
  '👌': { name: 'ok hand', keywords: ['hand', 'ok', '👌'] },
  '🤏': { name: 'pinching hand', keywords: ['hand', 'pinching', '🤏'] },
  '✌️': { name: 'victory hand', keywords: ['hand', 'victory', 'peace', '✌️'] },
  '🤞': { name: 'crossed fingers', keywords: ['hand', 'luck', '🤞'] },
  '🤟': { name: 'love-you gesture', keywords: ['hand', 'love', '🤟'] },
  '🤘': { name: 'sign of the horns', keywords: ['hand', 'rock', '🤘'] },
  '🤙': { name: 'call me hand', keywords: ['hand', 'call', '🤙'] },
  '👈': { name: 'backhand index pointing left', keywords: ['hand', 'point', 'left', '👈'] },
  '👉': { name: 'backhand index pointing right', keywords: ['hand', 'point', 'right', '👉'] },
  '👆': { name: 'backhand index pointing up', keywords: ['hand', 'point', 'up', '👆'] },
  '🖕': { name: 'middle finger', keywords: ['hand', 'middle finger', '🖕'] },
  '👇': { name: 'backhand index pointing down', keywords: ['hand', 'point', 'down', '👇'] },
  '☝️': { name: 'index pointing up', keywords: ['hand', 'point', 'up', '☝️'] },
  '👍': { name: 'thumbs up', keywords: ['hand', 'like', '👍'] },
  '👎': { name: 'thumbs down', keywords: ['hand', 'dislike', '👎'] },
  '👊': { name: 'oncoming fist', keywords: ['hand', 'fist', 'punch', '👊'] },
  '✊': { name: 'raised fist', keywords: ['hand', 'fist', 'protest', '✊'] },
  '🤛': { name: 'left-facing fist', keywords: ['hand', 'fist', '🤛'] },
  '🤜': { name: 'right-facing fist', keywords: ['hand', 'fist', '🤜'] },
  '👏': { name: 'clapping hands', keywords: ['hand', 'clap', '👏'] },
  '🙌': { name: 'raising hands', keywords: ['hand', 'celebration', '🙌'] },
  '👐': { name: 'open hands', keywords: ['hand', 'open', '👐'] },
  '🤲': { name: 'palms up together', keywords: ['hand', 'prayer', '🤲'] },
  '🤝': { name: 'handshake', keywords: ['hand', 'agreement', '🤝'] },
  '🙏': { name: 'folded hands', keywords: ['hand', 'prayer', 'thanks', '🙏'] },
  '✍️': { name: 'writing hand', keywords: ['hand', 'write', '✍️'] },
  '💅': { name: 'nail polish', keywords: ['hand', 'beauty', '💅'] },
  '🤳': { name: 'selfie', keywords: ['hand', 'phone', '🤳'] },
  '💪': { name: 'flexed biceps', keywords: ['muscle', 'strong', '💪'] },
  '🦾': { name: 'mechanical arm', keywords: ['robot', 'prosthetic', '🦾'] },
  '🦿': { name: 'mechanical leg', keywords: ['robot', 'prosthetic', '🦿'] },
  '🦵': { name: 'leg', keywords: ['kick', '🦵'] },
  '🦶': { name: 'foot', keywords: ['kick', '🦶'] },
  '👂': { name: 'ear', keywords: ['hear', 'listen', '👂'] },
  '🦻': { name: 'ear with hearing aid', keywords: ['hearing', 'disability', '🦻'] },
  '👃': { name: 'nose', keywords: ['smell', '👃'] },
  '🧠': { name: 'brain', keywords: ['mind', 'smart', '🧠'] },
  '🦷': { name: 'tooth', keywords: ['dentist', '🦷'] },
  '🦴': { name: 'bone', keywords: ['skeleton', '🦴'] },
  '👀': { name: 'eyes', keywords: ['look', 'see', '👀'] },
  '👁️': { name: 'eye', keywords: ['look', 'see', '👁️'] },
  '👅': { name: 'tongue', keywords: ['taste', '👅'] },
  '👄': { name: 'mouth', keywords: ['kiss', 'lips', '👄'] },
  '💋': { name: 'kiss mark', keywords: ['lips', 'love', '💋'] },
  '🐶': { name: 'dog face', keywords: ['animal', 'pet', '🐶'] },
  '🐱': { name: 'cat face', keywords: ['animal', 'pet', '🐱'] },
  '🐭': { name: 'mouse face', keywords: ['animal', 'pet', '🐭'] },
  '🐹': { name: 'hamster', keywords: ['animal', 'pet', '🐹'] },
  '🐰': { name: 'rabbit face', keywords: ['animal', 'pet', 'bunny', '🐰'] },
  '🦊': { name: 'fox', keywords: ['animal', '🦊'] },
  '🐻': { name: 'bear', keywords: ['animal', '🐻'] },
  '🐼': { name: 'panda', keywords: ['animal', 'bear', '🐼'] },
  '🐨': { name: 'koala', keywords: ['animal', 'bear', '🐨'] },
  '🐯': { name: 'tiger face', keywords: ['animal', 'cat', '🐯'] },
  '🦁': { name: 'lion', keywords: ['animal', 'cat', 'king', '🦁'] },
  '🐮': { name: 'cow face', keywords: ['animal', 'farm', '🐮'] },
  '🐷': { name: 'pig face', keywords: ['animal', 'farm', '🐷'] },
  '🐽': { name: 'pig nose', keywords: ['animal', 'farm', '🐽'] },
  '🐸': { name: 'frog', keywords: ['animal', 'amphibian', '🐸'] },
  '🐵': { name: 'monkey face', keywords: ['animal', 'primate', '🐵'] },
  '🙈': { name: 'see-no-evil monkey', keywords: ['animal', 'monkey', '🙈'] },
  '🙉': { name: 'hear-no-evil monkey', keywords: ['animal', 'monkey', '🙉'] },
  '🙊': { name: 'speak-no-evil monkey', keywords: ['animal', 'monkey', '🙊'] },
  '🐒': { name: 'monkey', keywords: ['animal', 'primate', '🐒'] },
  '🐔': { name: 'chicken', keywords: ['animal', 'bird', 'farm', '🐔'] },
  '🐧': { name: 'penguin', keywords: ['animal', 'bird', '🐧'] },
  '🐦': { name: 'bird', keywords: ['animal', '🐦'] },
  '🐤': { name: 'baby chick', keywords: ['animal', 'bird', 'baby', '🐤'] },
  '🐣': { name: 'hatching chick', keywords: ['animal', 'bird', 'baby', '🐣'] },
  '🐥': { name: 'front-facing baby chick', keywords: ['animal', 'bird', 'baby', '🐥'] },
  '🦆': { name: 'duck', keywords: ['animal', 'bird', '🦆'] },
  '🦅': { name: 'eagle', keywords: ['animal', 'bird', '🦅'] },
  '🦉': { name: 'owl', keywords: ['animal', 'bird', 'wise', '🦉'] },
  '🦇': { name: 'bat', keywords: ['animal', 'mammal', '🦇'] },
  '🐺': { name: 'wolf', keywords: ['animal', 'mammal', '🐺'] },
  '🐗': { name: 'boar', keywords: ['animal', 'mammal', '🐗'] },
  '🐴': { name: 'horse face', keywords: ['animal', 'mammal', '🐴'] },
  '🦄': { name: 'unicorn', keywords: ['animal', 'mythical', '🦄'] },
  '🐝': { name: 'honeybee', keywords: ['insect', 'bee', '🐝'] },
  '🐛': { name: 'bug', keywords: ['insect', 'caterpillar', '🐛'] },
  '🦋': { name: 'butterfly', keywords: ['insect', '🦋'] },
  '🐌': { name: 'snail', keywords: ['mollusk', '🐌'] },
  '🐞': { name: 'lady beetle', keywords: ['insect', 'ladybug', '🐞'] },
  '🐜': { name: 'ant', keywords: ['insect', '🐜'] },
  '🦟': { name: 'mosquito', keywords: ['insect', '🦟'] },
  '🦗': { name: 'cricket', keywords: ['insect', '🦗'] },
  '🕷️': { name: 'spider', keywords: ['arachnid', '🕷️'] },
  '🕸️': { name: 'spider web', keywords: ['arachnid', '🕸️'] },
  '🦂': { name: 'scorpion', keywords: ['arachnid', '🦂'] },
  '🐢': { name: 'turtle', keywords: ['reptile', '🐢'] },
  '🐍': { name: 'snake', keywords: ['reptile', '🐍'] },
  '🦎': { name: 'lizard', keywords: ['reptile', '🦎'] },
  '🦖': { name: 'T-Rex', keywords: ['dinosaur', 'reptile', '🦖'] },
  '🦕': { name: 'sauropod', keywords: ['dinosaur', 'reptile', '🦕'] },
  '🐙': { name: 'octopus', keywords: ['mollusk', '🐙'] },
  '🦑': { name: 'squid', keywords: ['mollusk', '🦑'] },
  '🦐': { name: 'shrimp', keywords: ['crustacean', '🦐'] },
  '🦞': { name: 'lobster', keywords: ['crustacean', '🦞'] },
  '🦀': { name: 'crab', keywords: ['crustacean', '🦀'] },
  '🐡': { name: 'blowfish', keywords: ['fish', '🐡'] },
  '🐠': { name: 'tropical fish', keywords: ['fish', '🐠'] },
  '🐟': { name: 'fish', keywords: ['🐟'] },
  '🐬': { name: 'dolphin', keywords: ['mammal', 'marine', '🐬'] },
  '🐳': { name: 'spouting whale', keywords: ['mammal', 'marine', '🐳'] },
  '🐋': { name: 'whale', keywords: ['mammal', 'marine', '🐋'] },
  '🦈': { name: 'shark', keywords: ['fish', 'marine', '🦈'] },
  '🐊': { name: 'crocodile', keywords: ['reptile', '🐊'] },
  '🐅': { name: 'tiger', keywords: ['animal', 'cat', '🐅'] },
  '🐆': { name: 'leopard', keywords: ['animal', 'cat', '🐆'] },
  '🦓': { name: 'zebra', keywords: ['animal', 'mammal', '🦓'] },
  '🦍': { name: 'gorilla', keywords: ['animal', 'primate', '🦍'] },
  '🦧': { name: 'orangutan', keywords: ['animal', 'primate', '🦧'] },
  '🐘': { name: 'elephant', keywords: ['animal', 'mammal', '🐘'] },
  '🦛': { name: 'hippopotamus', keywords: ['animal', 'mammal', '🦛'] },
  '🦏': { name: 'rhinoceros', keywords: ['animal', 'mammal', '🦏'] },
  '🐪': { name: 'camel', keywords: ['animal', 'mammal', '🐪'] },
  '🐫': { name: 'two-hump camel', keywords: ['animal', 'mammal', '🐫'] },
  '🦒': { name: 'giraffe', keywords: ['animal', 'mammal', '🦒'] },
  '🦘': { name: 'kangaroo', keywords: ['animal', 'mammal', '🦘'] },
  '🐃': { name: 'water buffalo', keywords: ['animal', 'mammal', '🐃'] },
  '🐂': { name: 'ox', keywords: ['animal', 'mammal', '🐂'] },
  '🐄': { name: 'cow', keywords: ['animal', 'mammal', '🐄'] },
  '🐎': { name: 'horse', keywords: ['animal', 'mammal', '🐎'] },
  '🐖': { name: 'pig', keywords: ['animal', 'mammal', '🐖'] },
  '🐏': { name: 'ram', keywords: ['animal', 'mammal', '🐏'] },
  '🐑': { name: 'ewe', keywords: ['animal', 'mammal', '🐑'] },
  '🦙': { name: 'llama', keywords: ['animal', 'mammal', '🦙'] },
  '🐐': { name: 'goat', keywords: ['animal', 'mammal', '🐐'] },
  '🦌': { name: 'deer', keywords: ['animal', 'mammal', '🦌'] },
  '🐕': { name: 'dog', keywords: ['animal', 'mammal', '🐕'] },
  '🐩': { name: 'poodle', keywords: ['animal', 'mammal', '🐩'] },
  '🦮': { name: 'guide dog', keywords: ['animal', 'mammal', 'disability', '🦮'] },
  '🐕‍🦺': { name: 'service dog', keywords: ['animal', 'mammal', 'disability', '🐕‍🦺'] },
  '🐈': { name: 'cat', keywords: ['animal', 'mammal', '🐈'] },
  '🐓': { name: 'rooster', keywords: ['animal', 'bird', '🐓'] },
  '🦃': { name: 'turkey', keywords: ['animal', 'bird', '🦃'] },
  '🦚': { name: 'peacock', keywords: ['animal', 'bird', '🦚'] },
  '🦜': { name: 'parrot', keywords: ['animal', 'bird', '🦜'] },
  '🦢': { name: 'swan', keywords: ['animal', 'bird', '🦢'] },
  '🦩': { name: 'flamingo', keywords: ['animal', 'bird', '🦩'] },
  '🕊️': { name: 'dove', keywords: ['animal', 'bird', 'peace', '🕊️'] },
  '🐇': { name: 'rabbit', keywords: ['animal', 'mammal', '🐇'] },
  '🦝': { name: 'raccoon', keywords: ['animal', 'mammal', '🦝'] },
  '🦨': { name: 'skunk', keywords: ['animal', 'mammal', '🦨'] },
  '🦡': { name: 'badger', keywords: ['animal', 'mammal', '🦡'] },
  '🦦': { name: 'otter', keywords: ['animal', 'mammal', '🦦'] },
  '🦥': { name: 'sloth', keywords: ['animal', 'mammal', '🦥'] },
  '🐁': { name: 'mouse', keywords: ['animal', 'mammal', '🐁'] },
  '🐀': { name: 'rat', keywords: ['animal', 'mammal', '🐀'] },
  '🐿️': { name: 'chipmunk', keywords: ['animal', 'mammal', '🐿️'] },
  '🦔': { name: 'hedgehog', keywords: ['animal', 'mammal', '🦔'] },
  '🐾': { name: 'paw prints', keywords: ['animal', 'paw', '🐾'] },
  '🐉': { name: 'dragon', keywords: ['mythical', 'fantasy', '🐉'] },
  '🐲': { name: 'dragon face', keywords: ['mythical', 'fantasy', '🐲'] },
  '🌵': { name: 'cactus', keywords: ['plant', 'desert', '🌵'] },
  '🎄': { name: 'christmas tree', keywords: ['plant', 'holiday', '🎄'] },
  '🌲': { name: 'evergreen tree', keywords: ['plant', 'tree', '🌲'] },
  '🌳': { name: 'deciduous tree', keywords: ['plant', 'tree', '🌳'] },
  '🌴': { name: 'palm tree', keywords: ['plant', 'tree', '🌴'] },
  '🌱': { name: 'seedling', keywords: ['plant', 'new', '🌱'] },
  '🌿': { name: 'herb', keywords: ['plant', 'leaf', '🌿'] },
  '☘️': { name: 'shamrock', keywords: ['plant', 'luck', '☘️'] },
  '🍀': { name: 'four leaf clover', keywords: ['plant', 'luck', '🍀'] },
  '🎍': { name: 'pine decoration', keywords: ['plant', 'bamboo', '🎍'] },
  '🎋': { name: 'tanabata tree', keywords: ['plant', 'bamboo', '🎋'] },
  '🍃': { name: 'leaf fluttering in wind', keywords: ['plant', 'leaf', '🍃'] },
  '🍂': { name: 'fallen leaf', keywords: ['plant', 'leaf', 'autumn', '🍂'] },
  '🍁': { name: 'maple leaf', keywords: ['plant', 'leaf', 'canada', '🍁'] },
  '🍄': { name: 'mushroom', keywords: ['plant', 'fungus', '🍄'] },
  '🐚': { name: 'spiral shell', keywords: ['sea', 'shell', '🐚'] },
  '🌾': { name: 'sheaf of rice', keywords: ['plant', 'grain', '🌾'] },
  '💐': { name: 'bouquet', keywords: ['flower', 'plant', '💐'] },
  '🌷': { name: 'tulip', keywords: ['flower', 'plant', '🌷'] },
  '🌹': { name: 'rose', keywords: ['flower', 'plant', 'love', '🌹'] },
  '🥀': { name: 'wilted flower', keywords: ['flower', 'plant', 'sad', '🥀'] },
  '🌺': { name: 'hibiscus', keywords: ['flower', 'plant', '🌺'] },
  '🌸': { name: 'cherry blossom', keywords: ['flower', 'plant', 'japan', '🌸'] },
  '🌼': { name: 'blossom', keywords: ['flower', 'plant', '🌼'] },
  '🌻': { name: 'sunflower', keywords: ['flower', 'plant', '🌻'] },
  '🌞': { name: 'sun with face', keywords: ['weather', 'sun', '🌞'] },
  '🌝': { name: 'full moon face', keywords: ['weather', 'moon', '🌝'] },
  '🌛': { name: 'first quarter moon face', keywords: ['weather', 'moon', '🌛'] },
  '🌜': { name: 'last quarter moon face', keywords: ['weather', 'moon', '🌜'] },
  '🌚': { name: 'new moon face', keywords: ['weather', 'moon', '🌚'] },
  '🌕': { name: 'full moon', keywords: ['weather', 'moon', '🌕'] },
  '🌖': { name: 'waning gibbous moon', keywords: ['weather', 'moon', '🌖'] },
  '🌗': { name: 'last quarter moon', keywords: ['weather', 'moon', '🌗'] },
  '🌘': { name: 'waning crescent moon', keywords: ['weather', 'moon', '🌘'] },
  '🌑': { name: 'new moon', keywords: ['weather', 'moon', '🌑'] },
  '🌒': { name: 'waxing crescent moon', keywords: ['weather', 'moon', '🌒'] },
  '🌓': { name: 'first quarter moon', keywords: ['weather', 'moon', '🌓'] },
  '🌔': { name: 'waxing gibbous moon', keywords: ['weather', 'moon', '🌔'] },
  '🌙': { name: 'crescent moon', keywords: ['weather', 'moon', '🌙'] },
  '🌎': { name: 'globe showing americas', keywords: ['world', 'earth', '🌎'] },
  '🌍': { name: 'globe showing europe-africa', keywords: ['world', 'earth', '🌍'] },
  '🌏': { name: 'globe showing asia-australia', keywords: ['world', 'earth', '🌏'] },
  '🪐': { name: 'ringed planet', keywords: ['space', 'saturn', '🪐'] },
  '💫': { name: 'dizzy', keywords: ['star', 'space', '💫'] },
  '⭐': { name: 'star', keywords: ['space', '⭐'] },
  '🌟': { name: 'glowing star', keywords: ['space', 'star', '🌟'] },
  '✨': { name: 'sparkles', keywords: ['star', 'magic', '✨'] },
  '⚡': { name: 'high voltage', keywords: ['lightning', 'electricity', '⚡'] },
  '☄️': { name: 'comet', keywords: ['space', '☄️'] },
  '💥': { name: 'collision', keywords: ['boom', 'explode', '💥'] },
  '🍎': { name: 'red apple', keywords: ['fruit', 'teacher', 'red', 'apple'] },
  '🍊': { name: 'tangerine', keywords: ['orange', 'fruit', 'citrus', 'tangerine'] },
  '🍋': { name: 'lemon', keywords: ['fruit', 'citrus', 'lemon'] },
  '🍌': { name: 'banana', keywords: ['fruit', 'yellow', 'banana'] },
  '🍉': { name: 'watermelon', keywords: ['fruit', 'summer', 'watermelon'] },
  '🍇': { name: 'grapes', keywords: ['fruit', 'wine', 'grapes'] },
  '🍓': { name: 'strawberry', keywords: ['fruit', 'berry', 'strawberry'] },
  '🫐': { name: 'blueberries', keywords: ['fruit', 'berry', 'blueberries'] },
  '🍈': { name: 'melon', keywords: ['fruit', 'honeydew', 'cantaloupe', 'melon'] },
  '🍒': { name: 'cherries', keywords: ['fruit', 'cherry', 'cherries'] },
  '🍑': { name: 'peach', keywords: ['fruit', 'pit', 'peach'] },
  '🥭': { name: 'mango', keywords: ['fruit', 'tropical', 'mango'] },
  '🍍': { name: 'pineapple', keywords: ['fruit', 'tropical', 'pineapple'] },
  '🥥': { name: 'coconut', keywords: ['fruit', 'tropical', 'coconut'] },
  '🥝': { name: 'kiwi fruit', keywords: ['fruit', 'tropical', 'kiwi'] },
  '🍅': { name: 'tomato', keywords: ['fruit', 'vegetable', 'tomato'] },
  '🍆': { name: 'eggplant', keywords: ['vegetable', 'aubergine', 'eggplant'] },
  '🥑': { name: 'avocado', keywords: ['fruit', 'vegetable', 'avocado'] },
  '🥦': { name: 'broccoli', keywords: ['vegetable', 'floret', 'broccoli'] },
  '🥬': { name: 'leafy green', keywords: ['vegetable', 'lettuce', 'cabbage', 'kale', 'spinach', 'leafy green'] },
  '🥒': { name: 'cucumber', keywords: ['vegetable', 'pickle', 'cucumber'] },
  '🌶️': { name: 'hot pepper', keywords: ['vegetable', 'spicy', 'chili', 'hot pepper'] },
  '🫑': { name: 'bell pepper', keywords: ['vegetable', 'pepper', 'bell pepper'] },
  '🌽': { name: 'ear of corn', keywords: ['vegetable', 'maize', 'corn'] },
  '🥕': { name: 'carrot', keywords: ['vegetable', 'orange', 'carrot'] },
  '🫒': { name: 'olive', keywords: ['fruit', 'mediterranean', 'olive'] },
  '🧄': { name: 'garlic', keywords: ['vegetable', 'flavoring', 'garlic'] },
  '🧅': { name: 'onion', keywords: ['vegetable', 'flavoring', 'onion'] },
  '🥔': { name: 'potato', keywords: ['vegetable', 'tuber', 'potato'] },
  '🍠': { name: 'roasted sweet potato', keywords: ['vegetable', 'tuber', 'sweet potato'] },
  '🥐': { name: 'croissant', keywords: ['bread', 'pastry', 'french', 'croissant'] },
  '🥯': { name: 'bagel', keywords: ['bread', 'schmear', 'bagel'] },
  '🍞': { name: 'bread', keywords: ['toast', 'loaf', 'bread'] },
  '🥖': { name: 'baguette bread', keywords: ['bread', 'french', 'baguette'] },
  '🥨': { name: 'pretzel', keywords: ['bread', 'twisted', 'pretzel'] },
  '🧀': { name: 'cheese wedge', keywords: ['dairy', 'cheese'] },
  '🥚': { name: 'egg', keywords: ['dairy', 'breakfast', 'egg'] },
  '🍳': { name: 'cooking', keywords: ['egg', 'breakfast', 'frying pan', 'cooking'] },
  '🧈': { name: 'butter', keywords: ['dairy', 'margarine', 'butter'] },
  '🥞': { name: 'pancakes', keywords: ['breakfast', 'flapjacks', 'hotcakes', 'pancakes'] },
  '🧇': { name: 'waffle', keywords: ['breakfast', 'belgian', 'waffle'] },
  '🥓': { name: 'bacon', keywords: ['pork', 'breakfast', 'bacon'] },
  '🥩': { name: 'cut of meat', keywords: ['beef', 'pork', 'steak', 'meat'] },
  '🍗': { name: 'poultry leg', keywords: ['chicken', 'turkey', 'drumstick', 'poultry'] },
  '🍖': { name: 'meat on bone', keywords: ['pork', 'beef', 'ribs', 'meat'] },
  '🌭': { name: 'hot dog', keywords: ['sausage', 'bun', 'frankfurter', 'hot dog'] },
  '🍔': { name: 'hamburger', keywords: ['beef', 'burger', 'cheeseburger', 'hamburger'] },
  '🍟': { name: 'french fries', keywords: ['potato', 'chips', 'fries'] },
  '🍕': { name: 'pizza', keywords: ['cheese', 'pepperoni', 'pie', 'pizza'] },
  '🫓': { name: 'flatbread', keywords: ['naan', 'pita', 'roti', 'flatbread'] },
  '🥪': { name: 'sandwich', keywords: ['bread', 'lunch', 'sandwich'] },
  '🥙': { name: 'stuffed flatbread', keywords: ['pita', 'gyro', 'kebab', 'falafel', 'stuffed flatbread'] },
  '🧆': { name: 'falafel', keywords: ['chickpea', 'middle eastern', 'falafel'] },
  '🌮': { name: 'taco', keywords: ['mexican', 'shell', 'taco'] },
  '🌯': { name: 'burrito', keywords: ['mexican', 'wrap', 'burrito'] },
  '🫔': { name: 'tamale', keywords: ['mexican', 'masa', 'tamale'] },
  '🥗': { name: 'green salad', keywords: ['vegetable', 'healthy', 'salad'] },
  '🥘': { name: 'shallow pan of food', keywords: ['paella', 'spanish', 'casserole', 'pan'] },
  '🫕': { name: 'fondue', keywords: ['cheese', 'chocolate', 'swiss', 'fondue'] },
  '🍝': { name: 'spaghetti', keywords: ['pasta', 'italian', 'noodles', 'spaghetti'] },
  '🍜': { name: 'steaming bowl', keywords: ['ramen', 'noodles', 'japanese', 'soup', 'bowl'] },
  '🍲': { name: 'pot of food', keywords: ['soup', 'stew', 'casserole', 'pot'] },
  '🍛': { name: 'curry rice', keywords: ['indian', 'japanese', 'thai', 'curry'] },
  '🍣': { name: 'sushi', keywords: ['japanese', 'fish', 'rice', 'sushi'] },
  '🍱': { name: 'bento box', keywords: ['japanese', 'lunchbox', 'bento'] },
  '🥟': { name: 'dumpling', keywords: ['chinese', 'potsticker', 'gyoza', 'dumpling'] },
  '🦪': { name: 'oyster', keywords: ['seafood', 'shellfish', 'oyster'] },
  '🍤': { name: 'fried shrimp', keywords: ['seafood', 'tempura', 'prawn', 'shrimp'] },
  '🍙': { name: 'rice ball', keywords: ['japanese', 'onigiri', 'rice'] },
  '🍚': { name: 'cooked rice', keywords: ['steamed', 'white', 'rice'] },
  '🍘': { name: 'rice cracker', keywords: ['japanese', 'senbei', 'cracker'] },
  '🍥': { name: 'fish cake with swirl', keywords: ['japanese', 'narutomaki', 'kamaboko', 'fish cake'] },
  '🥠': { name: 'fortune cookie', keywords: ['chinese', 'prophecy', 'cookie'] },
  '🥮': { name: 'moon cake', keywords: ['chinese', 'festival', 'pastry', 'moon cake'] },
  '🍢': { name: 'oden', keywords: ['japanese', 'skewer', 'broth', 'oden'] },
  '🍡': { name: 'dango', keywords: ['japanese', 'dessert', 'skewer', 'dango'] },
  '🍧': { name: 'shaved ice', keywords: ['dessert', 'hawaiian', 'kakigori', 'ice'] },
  '🍨': { name: 'ice cream', keywords: ['dessert', 'sundae', 'ice cream'] },
  '🍦': { name: 'soft ice cream', keywords: ['dessert', 'cone', 'soft serve', 'ice cream'] },
  '🥧': { name: 'pie', keywords: ['dessert', 'pastry', 'filling', 'pie'] },
  '🧁': { name: 'cupcake', keywords: ['dessert', 'cake', 'icing', 'cupcake'] },
  '🍰': { name: 'shortcake', keywords: ['dessert', 'cake', 'strawberry', 'shortcake'] },
  '🎂': { name: 'birthday cake', keywords: ['dessert', 'celebration', 'party', 'cake'] },
  '🍮': { name: 'custard', keywords: ['dessert', 'flan', 'pudding', 'custard'] },
  '🍭': { name: 'lollipop', keywords: ['dessert', 'candy', 'sucker', 'lollipop'] },
  '🍬': { name: 'candy', keywords: ['dessert', 'sweet', 'gummy', 'candy'] },
  '🍫': { name: 'chocolate bar', keywords: ['dessert', 'candy', 'cocoa', 'chocolate'] },
  '🍿': { name: 'popcorn', keywords: ['snack', 'movie', 'corn', 'popcorn'] },
  '🍩': { name: 'doughnut', keywords: ['dessert', 'donut', 'sprinkles', 'doughnut'] },
  '🍪': { name: 'cookie', keywords: ['dessert', 'chocolate chip', 'biscuit', 'cookie'] },
  '🌰': { name: 'chestnut', keywords: ['nut', 'roasting', 'christmas', 'chestnut'] },
  '🥜': { name: 'peanuts', keywords: ['nut', 'legume', 'peanut'] },
  '🍯': { name: 'honey pot', keywords: ['sweetener', 'bee', 'honey'] },
  '🥛': { name: 'glass of milk', keywords: ['drink', 'dairy', 'calcium', 'milk'] },
  '🍼': { name: 'baby bottle', keywords: ['drink', 'milk', 'infant', 'baby'] },
  '☕': { name: 'hot beverage', keywords: ['drink', 'coffee', 'tea', 'espresso', 'beverage'] },
  '🫖': { name: 'teapot', keywords: ['drink', 'tea', 'kettle', 'teapot'] },
  '🍵': { name: 'teacup without handle', keywords: ['drink', 'tea', 'green tea', 'matcha', 'teacup'] },
  '🧃': { name: 'juice box', keywords: ['drink', 'fruit', 'carton', 'juice'] },
  '🥤': { name: 'cup with straw', keywords: ['drink', 'soda', 'juice', 'takeaway', 'cup'] },
  '🧋': { name: 'bubble tea', keywords: ['drink', 'boba', 'pearl milk tea', 'bubble tea'] },
  '🍶': { name: 'sake', keywords: ['drink', 'japanese', 'rice wine', 'sake'] },
  '🍺': { name: 'beer mug', keywords: ['drink', 'ale', 'lager', 'pint', 'beer'] },
  '🍻': { name: 'clinking beer mugs', keywords: ['drink', 'cheers', 'toast', 'beer'] },
  '🥂': { name: 'clinking glasses', keywords: ['drink', 'cheers', 'toast', 'champagne', 'prosecco'] },
  '🍷': { name: 'wine glass', keywords: ['drink', 'red', 'white', 'cabernet', 'merlot', 'wine'] },
  '🥃': { name: 'tumbler glass', keywords: ['drink', 'whiskey', 'bourbon', 'scotch', 'glass'] },
  '🍸': { name: 'cocktail glass', keywords: ['drink', 'martini', 'manhattan', 'cocktail'] },
  '🍹': { name: 'tropical drink', keywords: ['drink', 'vacation', 'pineapple', 'cocktail'] },
  '🧉': { name: 'mate', keywords: ['drink', 'south american', 'yerba', 'mate'] },
  '🍾': { name: 'bottle with popping cork', keywords: ['drink', 'champagne', 'prosecco', 'celebration', 'bottle'] },
  '🧊': { name: 'ice cube', keywords: ['frozen', 'water', 'cold', 'ice'] },
  '🥄': { name: 'spoon', keywords: ['cutlery', 'utensil', 'spoon'] },
  '🍴': { name: 'fork and knife', keywords: ['cutlery', 'utensil', 'dining', 'fork', 'knife'] },
  '🍽️': { name: 'fork and knife with plate', keywords: ['cutlery', 'utensil', 'dining', 'eating', 'plate'] },
  '🥣': { name: 'bowl with spoon', keywords: ['cutlery', 'utensil', 'cereal', 'soup', 'bowl'] },
  '🥡': { name: 'takeout box', keywords: ['food', 'chinese', 'oyster pail', 'takeout'] },
  '🥢': { name: 'chopsticks', keywords: ['cutlery', 'utensil', 'asian', 'chopsticks'] },
  '🧂': { name: 'salt', keywords: ['condiment', 'shaker', 'sodium', 'salt'] },
  '⚽': { name: 'soccer ball', keywords: ['sport', 'football', 'soccer'] },
  '🏀': { name: 'basketball', keywords: ['sport', 'hoops', 'basketball'] },
  '🏈': { name: 'american football', keywords: ['sport', 'nfl', 'gridiron', 'football'] },
  '⚾': { name: 'baseball', keywords: ['sport', 'mlb', 'diamond', 'baseball'] },
  '🥎': { name: 'softball', keywords: ['sport', 'underhand', 'softball'] },
  '🎾': { name: 'tennis', keywords: ['sport', 'racket', 'wimbledon', 'tennis'] },
  '🏐': { name: 'volleyball', keywords: ['sport', 'beach', 'net', 'volleyball'] },
  '🏉': { name: 'rugby football', keywords: ['sport', 'scrum', 'oval', 'rugby'] },
  '🥏': { name: 'flying disc', keywords: ['sport', 'frisbee', 'ultimate', 'disc'] },
  '🎱': { name: 'pool 8 ball', keywords: ['game', 'billiards', 'pool', 'eight ball'] },
  '🪀': { name: 'yo-yo', keywords: ['toy', 'game', 'string', 'yo-yo'] },
  '🏓': { name: 'ping pong', keywords: ['game', 'table tennis', 'paddle', 'ping pong'] },
  '🏸': { name: 'badminton', keywords: ['sport', 'shuttlecock', 'racket', 'badminton'] },
  '🏒': { name: 'ice hockey', keywords: ['sport', 'puck', 'stick', 'hockey'] },
  '🏑': { name: 'field hockey', keywords: ['sport', 'stick', 'ball', 'hockey'] },
  '🥍': { name: 'lacrosse', keywords: ['sport', 'stick', 'net', 'lacrosse'] },
  '🏏': { name: 'cricket game', keywords: ['sport', 'bat', 'ball', 'wicket', 'cricket'] },
  '🪃': { name: 'boomerang', keywords: ['toy', 'australia', 'throwing', 'boomerang'] },
  '🥅': { name: 'goal net', keywords: ['sport', 'score', 'net', 'goal'] },
  '⛳': { name: 'flag in hole', keywords: ['sport', 'golf', 'green', 'hole'] },
  '🪁': { name: 'kite', keywords: ['toy', 'wind', 'fly', 'kite'] },
  '🏹': { name: 'bow and arrow', keywords: ['weapon', 'archery', 'target', 'arrow'] },
  '🎣': { name: 'fishing pole', keywords: ['hobby', 'fish', 'reel', 'fishing'] },
  '🤿': { name: 'diving mask', keywords: ['activity', 'scuba', 'snorkel', 'diving'] },
  '🥊': { name: 'boxing glove', keywords: ['sport', 'fight', 'punch', 'boxing'] },
  '🥋': { name: 'martial arts uniform', keywords: ['sport', 'judo', 'karate', 'taekwondo', 'martial arts'] },
  '🎽': { name: 'running shirt', keywords: ['sport', 'marathon', 'race', 'running'] },
  '🛹': { name: 'skateboard', keywords: ['sport', 'deck', 'wheels', 'skateboarding'] },
  '🛼': { name: 'roller skate', keywords: ['sport', 'wheels', 'retro', 'roller skating'] },
  '🛷': { name: 'sled', keywords: ['activity', 'snow', 'winter', 'sledding'] },
  '⛸️': { name: 'ice skate', keywords: ['sport', 'winter', 'figure skating', 'ice skating'] },
  '🥌': { name: 'curling stone', keywords: ['sport', 'winter', 'ice', 'curling'] },
  '🎿': { name: 'skis', keywords: ['sport', 'winter', 'snow', 'skiing'] },
  '⛷️': { name: 'skier', keywords: ['sport', 'winter', 'snow', 'skiing'] },
  '🏂': { name: 'snowboarder', keywords: ['sport', 'winter', 'snow', 'snowboarding'] },
  '🪂': { name: 'parachute', keywords: ['activity', 'skydiving', 'jump', 'parachute'] },
  '🏋️‍♀️': { name: 'woman lifting weights', keywords: ['sport', 'gym', 'fitness', 'woman', 'weightlifting'] },
  '🏋️': { name: 'person lifting weights', keywords: ['sport', 'gym', 'fitness', 'weightlifting'] },
  '🤼‍♀️': { name: 'women wrestling', keywords: ['sport', 'wwe', 'grappling', 'women', 'wrestling'] },
  '🤼': { name: 'people wrestling', keywords: ['sport', 'wwe', 'grappling', 'wrestling'] },
  '🤸‍♀️': { name: 'woman cartwheeling', keywords: ['sport', 'gymnastics', 'flip', 'woman', 'cartwheel'] },
  '🤸': { name: 'person cartwheeling', keywords: ['sport', 'gymnastics', 'flip', 'cartwheel'] },
  '⛹️‍♀️': { name: 'woman bouncing ball', keywords: ['sport', 'basketball', 'dribble', 'woman'] },
  '⛹️': { name: 'person bouncing ball', keywords: ['sport', 'basketball', 'dribble'] },
  '🤺': { name: 'person fencing', keywords: ['sport', 'sword', 'epee', 'foil', 'sabre', 'fencing'] },
  '🤾‍♀️': { name: 'woman playing handball', keywords: ['sport', 'net', 'ball', 'woman', 'handball'] },
  '🤾': { name: 'person playing handball', keywords: ['sport', 'net', 'ball', 'handball'] },
  '🏌️‍♀️': { name: 'woman golfing', keywords: ['sport', 'caddy', 'swing', 'woman', 'golfing'] },
  '🏌️': { name: 'person golfing', keywords: ['sport', 'caddy', 'swing', 'golfing'] },
  '🏇': { name: 'horse racing', keywords: ['sport', 'jockey', 'derby', 'horse'] },
  '🧘‍♀️': { name: 'woman in lotus position', keywords: ['activity', 'meditation', 'zen', 'woman', 'yoga'] },
  '🧘': { name: 'person in lotus position', keywords: ['activity', 'meditation', 'zen', 'yoga'] },
  '🏄‍♀️': { name: 'woman surfing', keywords: ['sport', 'beach', 'wave', 'woman', 'surfing'] },
  '🏄': { name: 'person surfing', keywords: ['sport', 'beach', 'wave', 'surfing'] },
  '🏊‍♀️': { name: 'woman swimming', keywords: ['sport', 'pool', 'water', 'woman', 'swimming'] },
  '🏊': { name: 'person swimming', keywords: ['sport', 'pool', 'water', 'swimming'] },
  '🤽‍♀️': { name: 'woman playing water polo', keywords: ['sport', 'pool', 'water', 'woman', 'water polo'] },
  '🤽': { name: 'person playing water polo', keywords: ['sport', 'pool', 'water', 'water polo'] },
  '🚣‍♀️': { name: 'woman rowing boat', keywords: ['activity', 'water', 'oar', 'woman', 'rowing'] },
  '🚣': { name: 'person rowing boat', keywords: ['activity', 'water', 'oar', 'rowing'] },
  '🧗‍♀️': { name: 'woman climbing', keywords: ['activity', 'bouldering', 'rock climbing', 'woman'] },
  '🧗': { name: 'person climbing', keywords: ['activity', 'bouldering', 'rock climbing'] },
  '🚵‍♀️': { name: 'woman mountain biking', keywords: ['sport', 'bicycle', 'trail', 'woman', 'mountain biking'] },
  '🚵': { name: 'person mountain biking', keywords: ['sport', 'bicycle', 'trail', 'mountain biking'] },
  '🚴‍♀️': { name: 'woman biking', keywords: ['sport', 'bicycle', 'commute', 'woman', 'biking'] },
  '🚴': { name: 'person biking', keywords: ['sport', 'bicycle', 'commute', 'biking'] },
  '🏆': { name: 'trophy', keywords: ['award', 'prize', 'winner', 'trophy'] },
  '🥇': { name: '1st place medal', keywords: ['award', 'gold', 'winner', 'first'] },
  '🥈': { name: '2nd place medal', keywords: ['award', 'silver', 'second'] },
  '🥉': { name: '3rd place medal', keywords: ['award', 'bronze', 'third'] },
  '🏅': { name: 'sports medal', keywords: ['award', 'prize', 'medal'] },
  '🎖️': { name: 'military medal', keywords: ['award', 'military', 'honor', 'medal'] },
  '🏵️': { name: 'rosette', keywords: ['award', 'prize', 'ribbon', 'rosette'] },
  '🎗️': { name: 'reminder ribbon', keywords: ['awareness', 'support', 'cause', 'ribbon'] },
  '🎫': { name: 'ticket', keywords: ['event', 'admission', 'concert', 'movie', 'ticket'] },
  '🎟️': { name: 'admission tickets', keywords: ['event', 'admission', 'concert', 'movie', 'ticket'] },
  '🎪': { name: 'circus tent', keywords: ['event', 'carnival', 'big top', 'circus'] },
  '🤹': { name: 'person juggling', keywords: ['activity', 'multitask', 'skill', 'juggling'] },
  '🤹‍♀️': { name: 'woman juggling', keywords: ['activity', 'multitask', 'skill', 'woman', 'juggling'] },
  '🎭': { name: 'performing arts', keywords: ['activity', 'theater', 'drama', 'masks'] },
  '🩰': { name: 'ballet shoes', keywords: ['activity', 'dance', 'pointe', 'ballet'] },
  '🎨': { name: 'artist palette', keywords: ['hobby', 'painting', 'colors', 'art'] },
  '🎬': { name: 'clapper board', keywords: ['entertainment', 'movie', 'film', 'video'] },
  '🎤': { name: 'microphone', keywords: ['entertainment', 'sing', 'karaoke', 'speak'] },
  '🎧': { name: 'headphone', keywords: ['audio', 'music', 'listen', 'podcast'] },
  '🎼': { name: 'musical score', keywords: ['music', 'notes', 'sheet music', 'score'] },
  '🎵': { name: 'musical note', keywords: ['music', 'sound', 'melody', 'note'] },
  '🎶': { name: 'musical notes', keywords: ['music', 'sound', 'melody', 'notes'] },
  '🥁': { name: 'drum', keywords: ['music', 'percussion', 'beat', 'drum'] },
  '🪘': { name: 'long drum', keywords: ['music', 'percussion', 'djembe', 'conga'] },
  '🎹': { name: 'musical keyboard', keywords: ['music', 'instrument', 'piano', 'keyboard'] },
  '🎻': { name: 'violin', keywords: ['music', 'instrument', 'strings', 'orchestra'] },
  '🎺': { name: 'trumpet', keywords: ['music', 'instrument', 'brass', 'jazz'] },
  '🎸': { name: 'guitar', keywords: ['music', 'instrument', 'strings', 'rock'] },
  '🪕': { name: 'banjo', keywords: ['music', 'instrument', 'strings', 'folk'] },
  '🎷': { name: 'saxophone', keywords: ['music', 'instrument', 'brass', 'jazz'] },
  '🎯': { name: 'direct hit', keywords: ['game', 'target', 'bullseye', 'darts'] },
  '🎳': { name: 'bowling', keywords: ['game', 'pins', 'strike', 'alley'] },
  '🎮': { name: 'video game', keywords: ['game', 'controller', 'console', 'gaming'] },
  '🎰': { name: 'slot machine', keywords: ['game', 'gambling', 'casino', 'jackpot'] },
  '🚗': { name: 'car', keywords: ['vehicle', 'transportation', 'automobile', '🚗'] },
  '🚕': { name: 'taxi', keywords: ['vehicle', 'transportation', 'cab', '🚕'] },
  '🚙': { name: 'sport utility vehicle', keywords: ['vehicle', 'transportation', 'suv', '🚙'] },
  '🚌': { name: 'bus', keywords: ['vehicle', 'transportation', 'public transit', '🚌'] },
  '🚎': { name: 'trolleybus', keywords: ['vehicle', 'transportation', 'tram', '🚎'] },
  '🏎️': { name: 'racing car', keywords: ['vehicle', 'sport', 'race', '🏎️'] },
  '🚓': { name: 'police car', keywords: ['vehicle', 'law enforcement', 'police', '🚓'] },
  '🚑': { name: 'ambulance', keywords: ['vehicle', 'emergency', 'medical', '🚑'] },
  '🚒': { name: 'fire engine', keywords: ['vehicle', 'emergency', 'fire', '🚒'] },
  '🚐': { name: 'minibus', keywords: ['vehicle', 'transportation', 'van', '🚐'] },
  '🛻': { name: 'pickup truck', keywords: ['vehicle', 'transportation', 'truck', '🛻'] },
  '🚚': { name: 'delivery truck', keywords: ['vehicle', 'transportation', 'delivery', '🚚'] },
  '🚛': { name: 'articulated lorry', keywords: ['vehicle', 'transportation', 'truck', '🚛'] },
  '🚜': { name: 'tractor', keywords: ['vehicle', 'farm', 'agriculture', '🚜'] },
  '🦯': { name: 'probing cane', keywords: ['accessibility', 'blind', 'mobility', '🦯'] },
  '🦽': { name: 'manual wheelchair', keywords: ['accessibility', 'mobility', 'wheelchair', '🦽'] },
  '🦼': { name: 'motorized wheelchair', keywords: ['accessibility', 'mobility', 'wheelchair', '🦼'] },
  '🛴': { name: 'kick scooter', keywords: ['vehicle', 'transportation', 'scooter', '🛴'] },
  '🚲': { name: 'bicycle', keywords: ['vehicle', 'transportation', 'bike', '🚲'] },
  '🛵': { name: 'motor scooter', keywords: ['vehicle', 'transportation', 'scooter', '🛵'] },
  '🏍️': { name: 'motorcycle', keywords: ['vehicle', 'transportation', 'bike', '🏍️'] },
  '🛺': { name: 'auto rickshaw', keywords: ['vehicle', 'transportation', 'tuk tuk', '🛺'] },
  '🚨': { name: 'rotating light', keywords: ['emergency', 'police', 'ambulance', '🚨'] },
  '🚔': { name: 'oncoming police car', keywords: ['vehicle', 'law enforcement', 'police', '🚔'] },
  '🚍': { name: 'oncoming bus', keywords: ['vehicle', 'transportation', 'bus', '🚍'] },
  '🚘': { name: 'oncoming automobile', keywords: ['vehicle', 'transportation', 'car', '🚘'] },
  '🚖': { name: 'oncoming taxi', keywords: ['vehicle', 'transportation', 'taxi', '🚖'] },
  '🚡': { name: 'aerial tramway', keywords: ['transportation', 'cable car', 'gondola', '🚡'] },
  '🚠': { name: 'mountain cableway', keywords: ['transportation', 'cable car', 'mountain', '🚠'] },
  '🚟': { name: 'suspension railway', keywords: ['transportation', 'monorail', 'train', '🚟'] },
  '🚃': { name: 'tram car', keywords: ['transportation', 'tram', 'streetcar', '🚃'] },
  '🚋': { name: 'tram', keywords: ['transportation', 'tram', 'streetcar', '🚋'] },
  '🚞': { name: 'mountain railway', keywords: ['transportation', 'train', 'mountain', '🚞'] },
  '🚝': { name: 'monorail', keywords: ['transportation', 'train', 'monorail', '🚝'] },
  '🚄': { name: 'high-speed train', keywords: ['transportation', 'train', 'bullet', '🚄'] },
  '🚅': { name: 'bullet train', keywords: ['transportation', 'train', 'shinkansen', '🚅'] },
  '🚈': { name: 'light rail', keywords: ['transportation', 'train', 'tram', '🚈'] },
  '🚂': { name: 'locomotive', keywords: ['transportation', 'train', 'steam', '🚂'] },
  '🚆': { name: 'train', keywords: ['transportation', 'train', 'railway', '🚆'] },
  '🚇': { name: 'metro', keywords: ['transportation', 'subway', 'underground', '🚇'] },
  '🚊': { name: 'tram', keywords: ['transportation', 'tram', 'streetcar', '🚊'] },
  '🚉': { name: 'station', keywords: ['transportation', 'train', 'station', '🚉'] },
  '✈️': { name: 'airplane', keywords: ['transportation', 'flight', 'travel', '✈️'] },
  '🛫': { name: 'small airplane', keywords: ['transportation', 'flight', 'airplane', '🛫'] },
  '🛬': { name: 'airplane arrival', keywords: ['transportation', 'flight', 'landing', '🛬'] },
  '🛩️': { name: 'small airplane', keywords: ['transportation', 'flight', 'airplane', '🛩️'] },
  '💺': { name: 'seat', keywords: ['transportation', 'chair', 'sitting', '💺'] },
  '🛰️': { name: 'satellite', keywords: ['space', 'communication', 'orbit', '🛰️'] },
  '🚀': { name: 'rocket', keywords: ['space', 'launch', 'ship', '🚀'] },
  '🛸': { name: 'flying saucer', keywords: ['space', 'ufo', 'alien', '🛸'] },
  '🚁': { name: 'helicopter', keywords: ['transportation', 'flight', 'air', '🚁'] },
  '🛶': { name: 'canoe', keywords: ['transportation', 'boat', 'water', '🛶'] },
  '⛵': { name: 'sailboat', keywords: ['transportation', 'boat', 'sailing', '⛵'] },
  '🚤': { name: 'speedboat', keywords: ['transportation', 'boat', 'water', '🚤'] },
  '🛥️': { name: 'motor boat', keywords: ['transportation', 'boat', 'water', '🛥️'] },
  '🛳️': { name: 'passenger ship', keywords: ['transportation', 'boat', 'cruise', '🛳️'] },
  '⛴️': { name: 'ferry', keywords: ['transportation', 'boat', 'water', '⛴️'] },
  '🚢': { name: 'ship', keywords: ['transportation', 'boat', 'water', '🚢'] },
  '⚓': { name: 'anchor', keywords: ['ship', 'boat', 'maritime', '⚓'] },
  '⛽': { name: 'fuel pump', keywords: ['gas station', 'fuel', 'petrol', '⛽'] },
  '🚧': { name: 'construction', keywords: ['work', 'build', 'construction', '🚧'] },
  '🚦': { name: 'vertical traffic light', keywords: ['transportation', 'signal', 'light', '🚦'] },
  '🚥': { name: 'horizontal traffic light', keywords: ['transportation', 'signal', 'light', '🚥'] },
  '🗺️': { name: 'world map', keywords: ['location', 'direction', 'map', '🗺️'] },
  '🗿': { name: 'moai', keywords: ['statue', 'easter island', '🗿'] },
  '🗽': { name: 'Statue of Liberty', keywords: ['statue', 'new york', 'freedom', '🗽'] },
  '🗼': { name: 'Tokyo Tower', keywords: ['tower', 'tokyo', 'japan', '🗼'] },
  '🏰': { name: 'castle', keywords: ['building', 'royal', 'fortress', '🏰'] },
  '🏯': { name: 'Japanese castle', keywords: ['building', 'japan', 'fortress', '🏯'] },
  '🏟️': { name: 'stadium', keywords: ['sports', 'venue', 'arena', '🏟️'] },
  '🎡': { name: 'ferris wheel', keywords: ['amusement park', 'ride', 'carnival', '🎡'] },
  '🎢': { name: 'roller coaster', keywords: ['amusement park', 'ride', 'thrill', '🎢'] },
  '🎠': { name: 'carousel horse', keywords: ['amusement park', 'ride', 'horse', '🎠'] },
  '⛲': { name: 'fountain', keywords: ['water', 'decorative', '⛲'] },
  '⛱️': { name: 'umbrella on ground', keywords: ['beach', 'sun', 'shade', '⛱️'] },
  '🏖️': { name: 'beach with umbrella', keywords: ['beach', 'vacation', 'summer', '🏖️'] },
  '🏝️': { name: 'desert island', keywords: ['island', 'desert', 'beach', '🏝️'] },
  '🏜️': { name: 'desert', keywords: ['landscape', 'arid', 'sand', '🏜️'] },
  '🌋': { name: 'volcano', keywords: ['mountain', 'eruption', 'lava', '🌋'] },
  '⛰️': { name: 'mountain', keywords: ['nature', 'landscape', 'climbing', '⛰️'] },
  '🏔️': { name: 'snow capped mountain', keywords: ['mountain', 'snow', 'winter', '🏔️'] },
  '🗻': { name: 'Mount Fuji', keywords: ['mountain', 'japan', 'volcano', '🗻'] },
  '🏕️': { name: 'camping', keywords: ['outdoors', 'tent', 'camp', '🏕️'] },
  '⛺': { name: 'tent', keywords: ['camping', 'outdoors', 'shelter', '⛺'] },
  '🏠': { name: 'house', keywords: ['building', 'home', 'residence', '🏠'] },
  '🏡': { name: 'house with garden', keywords: ['building', 'home', 'garden', '🏡'] },
  '🏘️': { name: 'houses', keywords: ['buildings', 'homes', 'residences', '🏘️'] },
  '🏚️': { name: 'derelict house', keywords: ['building', 'abandoned', 'old', '🏚️'] },
  '🏗️': { name: 'building construction', keywords: ['construction', 'building', 'work', '🏗️'] },
  '🏭': { name: 'factory', keywords: ['building', 'industry', 'manufacturing', '🏭'] },
  '🏢': { name: 'office building', keywords: ['building', 'work', 'business', '🏢'] },
  '🏬': { name: 'department store', keywords: ['building', 'shopping', 'retail', '🏬'] },
  '🏣': { name: 'Japanese post office', keywords: ['building', 'japan', 'mail', '🏣'] },
  '🏤': { name: 'post office', keywords: ['building', 'mail', 'postal', '🏤'] },
  '🏥': { name: 'hospital', keywords: ['building', 'health', 'medical', '🏥'] },
  '🏦': { name: 'bank', keywords: ['building', 'money', 'finance', '🏦'] },
  '🏨': { name: 'hotel', keywords: ['building', 'accommodation', 'travel', '🏨'] },
  '🏪': { name: 'convenience store', keywords: ['building', 'shop', 'retail', '🏪'] },
  '🏫': { name: 'school', keywords: ['building', 'education', 'learning', '🏫'] },
  '🏩': { name: 'love hotel', keywords: ['building', 'romance', 'couple', '🏩'] },
  '💒': { name: 'wedding', keywords: ['marriage', 'ceremony', 'church', '💒'] },
  '🏛️': { name: 'classical building', keywords: ['building', 'architecture', 'classical', '🏛️'] },
  '⛪': { name: 'church', keywords: ['building', 'religion', 'christian', '⛪'] },
  '🕌': { name: 'mosque', keywords: ['building', 'religion', 'islam', '🕌'] },
  '🕍': { name: 'synagogue', keywords: ['building', 'religion', 'jewish', '🕍'] },
  '🛕': { name: 'hindu temple', keywords: ['building', 'religion', 'hindu', '🛕'] },
  '🕋': { name: 'kaaba', keywords: ['building', 'religion', 'islam', '🕋'] },
  '⛩️': { name: 'shinto shrine', keywords: ['building', 'religion', 'japan', '⛩️'] },
  '🛤️': { name: 'railway track', keywords: ['transportation', 'train', 'railway', '🛤️'] },
  '🛣️': { name: 'motorway', keywords: ['transportation', 'road', 'highway', '🛣️'] },
  '⌚': { name: 'watch', keywords: ['time', 'clock', '⌚'] },
  '📱': { name: 'mobile phone', keywords: ['phone', 'mobile', 'smartphone', '📱'] },
  '📲': { name: 'mobile phone with arrow', keywords: ['phone', 'mobile', 'call', '📲'] },
  '💻': { name: 'laptop', keywords: ['computer', 'technology', '💻'] },
  '⌨️': { name: 'keyboard', keywords: ['computer', 'type', '⌨️'] },
  '🖥️': { name: 'desktop computer', keywords: ['computer', 'technology', '🖥️'] },
  '🖨️': { name: 'printer', keywords: ['computer', 'print', '🖨️'] },
  '🖱️': { name: 'computer mouse', keywords: ['computer', 'click', '🖱️'] },
  '🖲️': { name: 'trackball', keywords: ['computer', 'click', '🖲️'] },
  '🕹️': { name: 'joystick', keywords: ['game', 'play', '🕹️'] },
  '🗜️': { name: 'clamp', keywords: ['tool', 'squeeze', '🗜️'] },
  '💽': { name: 'computer disk', keywords: ['computer', 'storage', '💽'] },
  '💾': { name: 'floppy disk', keywords: ['computer', 'storage', '💾'] },
  '💿': { name: 'optical disk', keywords: ['computer', 'storage', '💿'] },
  '📀': { name: 'dvd', keywords: ['computer', 'storage', '📀'] },
  '📼': { name: 'videocassette', keywords: ['video', 'recording', '📼'] },
  '📷': { name: 'camera', keywords: ['photo', 'picture', '📷'] },
  '📸': { name: 'camera with flash', keywords: ['photo', 'picture', '📸'] },
  '📹': { name: 'video camera', keywords: ['video', 'recording', '📹'] },
  '🎥': { name: 'movie camera', keywords: ['film', 'movie', '🎥'] },
  '📽️': { name: 'film projector', keywords: ['film', 'movie', '📽️'] },
  '🎞️': { name: 'film frames', keywords: ['film', 'movie', '🎞️'] },
  '📞': { name: 'telephone receiver', keywords: ['phone', 'call', '📞'] },
  '☎️': { name: 'telephone', keywords: ['phone', 'call', '☎️'] },
  '📟': { name: 'pager', keywords: ['phone', 'message', '📟'] },
  '📠': { name: 'fax machine', keywords: ['fax', 'document', '📠'] },
  '📺': { name: 'television', keywords: ['tv', 'show', '📺'] },
  '📻': { name: 'radio', keywords: ['music', 'broadcast', '📻'] },
  '🎙️': { name: 'studio microphone', keywords: ['music', 'recording', '🎙️'] },
  '🎚️': { name: 'level slider', keywords: ['music', 'volume', '🎚️'] },
  '🎛️': { name: 'control knobs', keywords: ['music', 'control', '🎛️'] },
  '🧭': { name: 'compass', keywords: ['navigation', 'direction', '🧭'] },
  '⏱️': { name: 'stopwatch', keywords: ['time', 'clock', '⏱️'] },
  '⏲️': { name: 'timer clock', keywords: ['time', 'clock', '⏲️'] },
  '⏰': { name: 'alarm clock', keywords: ['time', 'clock', '⏰'] },
  '🕰️': { name: 'mantelpiece clock', keywords: ['time', 'clock', '🕰️'] },
  '⌛': { name: 'hourglass done', keywords: ['time', 'clock', '⌛'] },
  '⏳': { name: 'hourglass not done', keywords: ['time', 'clock', '⏳'] },
  '📡': { name: 'satellite antenna', keywords: ['communication', 'satellite', '📡'] },
  '🔋': { name: 'battery', keywords: ['power', 'energy', '🔋'] },
  '🔌': { name: 'electric plug', keywords: ['power', 'electricity', '🔌'] },
  '💡': { name: 'light bulb', keywords: ['light', 'idea', '💡'] },
  '🔦': { name: 'flashlight', keywords: ['light', 'torch', '🔦'] },
  '🕯️': { name: 'candle', keywords: ['light', 'fire', '🕯️'] },
  '🪔': { name: 'diya lamp', keywords: ['light', 'lamp', '🪔'] },
  '🧯': { name: 'fire extinguisher', keywords: ['fire', 'safety', '🧯'] },
  '🛢️': { name: 'oil drum', keywords: ['oil', 'fuel', '🛢️'] },
  '💸': { name: 'money with wings', keywords: ['money', 'flying', '💸'] },
  '💵': { name: 'dollar banknote', keywords: ['money', 'dollar', '💵'] },
  '💴': { name: 'yen banknote', keywords: ['money', 'yen', '💴'] },
  '💶': { name: 'euro banknote', keywords: ['money', 'euro', '💶'] },
  '💷': { name: 'pound banknote', keywords: ['money', 'pound', '💷'] },
  '💰': { name: 'money bag', keywords: ['money', 'dollar', '💰'] },
  '💳': { name: 'credit card', keywords: ['money', 'payment', '💳'] },
  '💎': { name: 'gem stone', keywords: ['jewel', 'diamond', '💎'] },
  '⚖️': { name: 'balance scale', keywords: ['justice', 'law', '⚖️'] },
  '🧰': { name: 'toolbox', keywords: ['tools', 'repair', '🧰'] },
  '🔧': { name: 'wrench', keywords: ['tool', 'repair', '🔧'] },
  '🔨': { name: 'hammer', keywords: ['tool', 'build', '🔨'] },
  '⚒️': { name: 'hammer and pick', keywords: ['tools', 'build', '⚒️'] },
  '🛠️': { name: 'hammer and wrench', keywords: ['tools', 'build', '🛠️'] },
  '⛏️': { name: 'pick', keywords: ['tool', 'mine', '⛏️'] },
  '🔩': { name: 'nut and bolt', keywords: ['tool', 'fasten', '🔩'] },
  '⚙️': { name: 'gear', keywords: ['tool', 'machine', '⚙️'] },
  '🧱': { name: 'brick', keywords: ['building', 'construction', '🧱'] },
  '⛓️': { name: 'chains', keywords: ['chain', 'link', '⛓️'] },
  '🧲': { name: 'magnet', keywords: ['magnetic', 'attraction', '🧲'] },
  '🔫': { name: 'pistol', keywords: ['gun', 'weapon', '🔫'] },
  '💣': { name: 'bomb', keywords: ['explosion', 'danger', '💣'] },
  '🧨': { name: 'firecracker', keywords: ['firework', 'explosion', '🧨'] },
  '🪓': { name: 'axe', keywords: ['tool', 'chop', '🪓'] },
  '🔪': { name: 'kitchen knife', keywords: ['knife', 'cut', '🔪'] },
  '🗡️': { name: 'dagger', keywords: ['knife', 'weapon', '🗡️'] },
  '⚔️': { name: 'crossed swords', keywords: ['weapon', 'battle', '⚔️'] },
  '🛡️': { name: 'shield', keywords: ['protection', 'defense', '🛡️'] },
  '🚬': { name: 'cigarette', keywords: ['smoke', 'tobacco', '🚬'] },
  '⚰️': { name: 'coffin', keywords: ['death', 'funeral', '⚰️'] },
  '🪦': { name: 'headstone', keywords: ['death', 'grave', '🪦'] },
  '⚱️': { name: 'funeral urn', keywords: ['death', 'ashes', '⚱️'] },
  '🏺': { name: 'amphora', keywords: ['vase', 'jar', '🏺'] },
  '🔮': { name: 'crystal ball', keywords: ['fortune', 'magic', '🔮'] },
  '📿': { name: 'prayer beads', keywords: ['religion', 'prayer', '📿'] },
  '🧿': { name: 'nazar amulet', keywords: ['protection', 'evil eye', '🧿'] },
  '💈': { name: 'barber pole', keywords: ['haircut', 'barber', '💈'] },
  '⚗️': { name: 'alembic', keywords: ['science', 'chemistry', '⚗️'] },
  '🔭': { name: 'telescope', keywords: ['science', 'astronomy', '🔭'] },
  '🔬': { name: 'microscope', keywords: ['science', 'laboratory', '🔬'] },
  '🕳️': { name: 'hole', keywords: ['opening', 'empty', '🕳️'] },
  '🩹': { name: 'adhesive bandage', keywords: ['bandage', 'injury', '🩹'] },
  '🩺': { name: 'stethoscope', keywords: ['medical', 'doctor', '🩺'] },
  '💊': { name: 'pill', keywords: ['medicine', 'drug', '💊'] },
  '💉': { name: 'syringe', keywords: ['medicine', 'drug', '💉'] },
  '🩸': { name: 'drop of blood', keywords: ['blood', 'medical', '🩸'] },
  '🧬': { name: 'dna', keywords: ['science', 'biology', '🧬'] },
  '🦠': { name: 'microbe', keywords: ['germ', 'virus', '🦠'] },
  '🧫': { name: 'petri dish', keywords: ['science', 'laboratory', '🧫'] },
  '🧪': { name: 'test tube', keywords: ['science', 'laboratory', '🧪'] },
  '🌡️': { name: 'thermometer', keywords: ['temperature', 'weather', '🌡️'] },
  '🧹': { name: 'broom', keywords: ['cleaning', 'sweeping', '🧹'] },
  '🧺': { name: 'basket', keywords: ['laundry', 'cleaning', '🧺'] },
  '🧻': { name: 'roll of paper', keywords: ['toilet paper', 'bathroom', '🧻'] },
  '🚽': { name: 'toilet', keywords: ['bathroom', 'restroom', '🚽'] },
  '🚰': { name: 'potable water', keywords: ['water', 'drink', '🚰'] },
  '🚿': { name: 'shower', keywords: ['bathroom', 'clean', '🚿'] },
  '🛁': { name: 'bathtub', keywords: ['bathroom', 'clean', '🛁'] },
  '🛀': { name: 'person taking bath', keywords: ['bathroom', 'clean', '🛀'] },
  '🧼': { name: 'soap', keywords: ['clean', 'wash', '🧼'] },
  '🪒': { name: 'razor', keywords: ['shave', 'hair', '🪒'] },
  '🧽': { name: 'sponge', keywords: ['clean', 'wash', '🧽'] },
  '🧴': { name: 'lotion bottle', keywords: ['moisturizer', 'cream', '🧴'] },
  '❤️': { name: 'red heart', keywords: ['love', 'heart', '❤️'] },
  '🧡': { name: 'orange heart', keywords: ['love', 'heart', '🧡'] },
  '💛': { name: 'yellow heart', keywords: ['love', 'heart', '💛'] },
  '💚': { name: 'green heart', keywords: ['love', 'heart', '💚'] },
  '💙': { name: 'blue heart', keywords: ['love', 'heart', '💙'] },
  '💜': { name: 'purple heart', keywords: ['love', 'heart', '💜'] },
  '🖤': { name: 'black heart', keywords: ['love', 'heart', '🖤'] },
  '🤍': { name: 'white heart', keywords: ['love', 'heart', '🤍'] },
  '🤎': { name: 'brown heart', keywords: ['love', 'heart', '🤎'] },
  '💔': { name: 'broken heart', keywords: ['sad', 'heart', '💔'] },
  '❣️': { name: 'heart exclamation', keywords: ['love', 'heart', '❣️'] },
  '💕': { name: 'two hearts', keywords: ['love', 'heart', '💕'] },
  '💞': { name: 'revolving hearts', keywords: ['love', 'heart', '💞'] },
  '💓': { name: 'beating heart', keywords: ['love', 'heart', '💓'] },
  '💗': { name: 'growing heart', keywords: ['love', 'heart', '💗'] },
  '💖': { name: 'sparkling heart', keywords: ['love', 'heart', '💖'] },
  '💘': { name: 'heart with arrow', keywords: ['love', 'heart', '💘'] },
  '💝': { name: 'heart with ribbon', keywords: ['love', 'heart', '💝'] },
  '💟': { name: 'heart decoration', keywords: ['love', 'heart', '💟'] },
  '☮️': { name: 'peace symbol', keywords: ['peace', 'symbol', '☮️'] },
  '✝️': { name: 'latin cross', keywords: ['religion', 'christian', '✝️'] },
  '☪️': { name: 'star and crescent', keywords: ['religion', 'islam', '☪️'] },
  '🕉️': { name: 'om', keywords: ['religion', 'hindu', '🕉️'] },
  '☸️': { name: 'wheel of dharma', keywords: ['religion', 'buddhist', '☸️'] },
  '✡️': { name: 'star of david', keywords: ['religion', 'judaism', '✡️'] },
  '🔯': { name: 'dotted six-pointed star', keywords: ['religion', 'judaism', '🔯'] },
  '🕎': { name: 'menorah', keywords: ['religion', 'judaism', '🕎'] },
  '☯️': { name: 'yin yang', keywords: ['religion', 'taoism', '☯️'] },
  '☦️': { name: 'orthodox cross', keywords: ['religion', 'christian', '☦️'] },
  '🛐': { name: 'place of worship', keywords: ['religion', 'worship', '🛐'] },
  '⛎': { name: 'ophiuchus', keywords: ['zodiac', 'astrology', '⛎'] },
  '♈': { name: 'aries', keywords: ['zodiac', 'astrology', '♈'] },
  '♉': { name: 'taurus', keywords: ['zodiac', 'astrology', '♉'] },
  '♊': { name: 'gemini', keywords: ['zodiac', 'astrology', '♊'] },
  '♋': { name: 'cancer', keywords: ['zodiac', 'astrology', '♋'] },
  '♌': { name: 'leo', keywords: ['zodiac', 'astrology', '♌'] },
  '♍': { name: 'virgo', keywords: ['zodiac', 'astrology', '♍'] },
  '♎': { name: 'libra', keywords: ['zodiac', 'astrology', '♎'] },
  '♏': { name: 'scorpio', keywords: ['zodiac', 'astrology', '♏'] },
  '♐': { name: 'sagittarius', keywords: ['zodiac', 'astrology', '♐'] },
  '♑': { name: 'capricorn', keywords: ['zodiac', 'astrology', '♑'] },
  '♒': { name: 'aquarius', keywords: ['zodiac', 'astrology', '♒'] },
  '♓': { name: 'pisces', keywords: ['zodiac', 'astrology', '♓'] },
  '🆔': { name: 'id button', keywords: ['id', 'identity', '🆔'] },
  '⚛️': { name: 'atom symbol', keywords: ['science', 'physics', '⚛️'] },
  '🉑': { name: 'japanese "acceptable" button', keywords: ['acceptable', 'japanese', '🉑'] },
  '☢️': { name: 'radioactive', keywords: ['danger', 'radiation', '☢️'] },
  '☣️': { name: 'biohazard', keywords: ['danger', 'biohazard', '☣️'] },
  '📴': { name: 'mobile phone off', keywords: ['phone', 'off', '📴'] },
  '📳': { name: 'vibration mode', keywords: ['phone', 'vibration', '📳'] },
  '🈶': { name: 'japanese "not free of charge" button', keywords: ['paid', 'japanese', '🈶'] },
  '🈚': { name: 'japanese "free of charge" button', keywords: ['free', 'japanese', '🈚'] },
  '🈸': { name: 'japanese "application" button', keywords: ['application', 'japanese', '🈸'] },
  '🈺': { name: 'japanese "open for business" button', keywords: ['open', 'japanese', '🈺'] },
  '🈷️': { name: 'japanese "monthly amount" button', keywords: ['monthly', 'japanese', '🈷️'] },
  '✴️': { name: 'eight-pointed star', keywords: ['star', 'symbol', '✴️'] },
  '🆚': { name: 'vs button', keywords: ['versus', 'vs', '🆚'] },
  '💮': { name: 'japanese "white flower" button', keywords: ['flower', 'japanese', '💮'] },
  '🉐': { name: 'japanese "bargain" button', keywords: ['bargain', 'japanese', '🉐'] },
  '㊙️': { name: 'japanese "secret" button', keywords: ['secret', 'japanese', '㊙️'] },
  '㊗️': { name: 'japanese "congratulations" button', keywords: ['congratulations', 'japanese', '㊗️'] },
  '🈴': { name: 'japanese "passing grade" button', keywords: ['passing', 'japanese', '🈴'] },
  '🈵': { name: 'japanese "no vacancy" button', keywords: ['no vacancy', 'japanese', '🈵'] },
  '🈹': { name: 'japanese "discount" button', keywords: ['discount', 'japanese', '🈹'] },
  '🈲': { name: 'japanese "prohibited" button', keywords: ['prohibited', 'japanese', '🈲'] },
  '🅰️': { name: 'a button (blood type)', keywords: ['blood type', 'a', '🅰️'] },
  '🅱️': { name: 'b button (blood type)', keywords: ['blood type', 'b', '🅱️'] },
  '🆎': { name: 'ab button (blood type)', keywords: ['blood type', 'ab', '🆎'] },
  '🆑': { name: 'cl button', keywords: ['clear', 'cl', '🆑'] },
  '🅾️': { name: 'o button (blood type)', keywords: ['blood type', 'o', '🅾️'] },
  '🆘': { name: 'sos button', keywords: ['help', 'emergency', '🆘'] },
  '❌': { name: 'cross mark', keywords: ['no', 'wrong', '❌'] },
  '⭕': { name: 'hollow red circle', keywords: ['circle', '⭕'] },
  '🛑': { name: 'stop sign', keywords: ['stop', 'sign', '🛑'] },
  '⛔': { name: 'no entry', keywords: ['no entry', 'forbidden', '⛔'] },
  '📛': { name: 'name badge', keywords: ['badge', 'name', '📛'] },
  '🚫': { name: 'prohibited', keywords: ['prohibited', 'forbidden', '🚫'] },
  '💯': { name: 'hundred points', keywords: ['100', 'perfect', '💯'] },
  '💢': { name: 'anger symbol', keywords: ['anger', 'angry', '💢'] },
  '♨️': { name: 'hot springs', keywords: ['hot', 'springs', '♨️'] },
  '🚷': { name: 'no pedestrians', keywords: ['no pedestrians', 'forbidden', '🚷'] },
  '🚯': { name: 'no littering', keywords: ['no littering', 'forbidden', '🚯'] },
  '🚳': { name: 'no bicycles', keywords: ['no bicycles', 'forbidden', '🚳'] },
  '🚱': { name: 'non-potable water', keywords: ['water', 'non-potable', '🚱'] },
  '🔞': { name: 'no one under eighteen', keywords: ['18', 'underage', '🔞'] },
  '📵': { name: 'no mobile phones', keywords: ['no phones', 'forbidden', '📵'] },
  '🚭': { name: 'no smoking', keywords: ['no smoking', 'forbidden', '🚭'] },
  '❗': { name: 'exclamation mark', keywords: ['exclamation', '❗'] },
  '❕': { name: 'white exclamation mark', keywords: ['exclamation', '❕'] },
  '❓': { name: 'question mark', keywords: ['question', '❓'] },
  '❔': { name: 'white question mark', keywords: ['question', '❔'] },
  '‼️': { name: 'double exclamation mark', keywords: ['exclamation', '‼️'] },
  '⁉️': { name: 'exclamation question mark', keywords: ['exclamation', 'question', '⁉️'] },
  '🔅': { name: 'dim button', keywords: ['dim', 'low', '🔅'] },
  '🔆': { name: 'bright button', keywords: ['bright', 'high', '🔆'] },
  '〽️': { name: 'part alternation mark', keywords: ['alternation', '〽️'] },
  '⚠️': { name: 'warning', keywords: ['warning', 'caution', '⚠️'] },
  '🚸': { name: 'children crossing', keywords: ['children', 'crossing', '🚸'] },
  '🔱': { name: 'trident emblem', keywords: ['trident', 'emblem', '🔱'] },
  '⚜️': { name: 'fleur-de-lis', keywords: ['fleur-de-lis', '⚜️'] },
  '🔰': { name: 'japanese symbol for beginner', keywords: ['beginner', 'japanese', '🔰'] },
  '♻️': { name: 'recycling symbol', keywords: ['recycling', '♻️'] },
  '✅': { name: 'check mark button', keywords: ['check', '✅'] },
  '🈯': { name: 'japanese "reserved" button', keywords: ['reserved', 'japanese', '🈯'] },
  '💹': { name: 'chart increasing with yen', keywords: ['chart', 'yen', '💹'] },
  '❇️': { name: 'sparkle', keywords: ['sparkle', '❇️'] },
  '✳️': { name: 'eight-spoked asterisk', keywords: ['asterisk', '✳️'] },
  '❎': { name: 'cross mark button', keywords: ['cross', '❎'] },
  '🌐': { name: 'globe with meridians', keywords: ['globe', 'world', '🌐'] },
  '💠': { name: 'diamond with a dot', keywords: ['diamond', '💠'] },
  '🏁': { name: 'chequered flag', keywords: ['flag', 'chequered', '🏁'] },
  '🚩': { name: 'triangular flag', keywords: ['flag', 'triangular', '🚩'] },
  '🎌': { name: 'crossed flags', keywords: ['flag', 'crossed', '🎌'] },
  '🏴': { name: 'black flag', keywords: ['flag', 'black', '🏴'] },
  '🏳️': { name: 'white flag', keywords: ['flag', 'white', '🏳️'] },
  '🏳️‍🌈': { name: 'rainbow flag', keywords: ['flag', 'rainbow', 'pride', '🏳️‍🌈'] },
  '🏳️‍⚧️': { name: 'transgender flag', keywords: ['flag', 'transgender', '🏳️‍⚧️'] },
  '🏴‍☠️': { name: 'pirate flag', keywords: ['flag', 'pirate', '🏴‍☠️'] },
  '🇦🇫': { name: 'flag: Afghanistan', keywords: ['flag', 'afghanistan', '🇦🇫'] },
  '🇦🇽': { name: 'flag: Åland Islands', keywords: ['flag', 'aland islands', '🇦🇽'] },
  '🇦🇱': { name: 'flag: Albania', keywords: ['flag', 'albania', '🇦🇱'] },
  '🇩🇿': { name: 'flag: Algeria', keywords: ['flag', 'algeria', '🇩🇿'] },
  '🇦🇸': { name: 'flag: American Samoa', keywords: ['flag', 'american samoa', '🇦🇸'] },
  '🇦🇩': { name: 'flag: Andorra', keywords: ['flag', 'andorra', '🇦🇩'] },
  '🇦🇴': { name: 'flag: Angola', keywords: ['flag', 'angola', '🇦🇴'] },
  '🇦🇮': { name: 'flag: Anguilla', keywords: ['flag', 'anguilla', '🇦🇮'] },
  '🇦🇶': { name: 'flag: Antarctica', keywords: ['flag', 'antarctica', '🇦🇶'] },
  '🇦🇬': { name: 'flag: Antigua & Barbuda', keywords: ['flag', 'antigua', 'barbuda', '🇦🇬'] },
  '🇦🇷': { name: 'flag: Argentina', keywords: ['flag', 'argentina', '🇦🇷'] },
  '🇦🇲': { name: 'flag: Armenia', keywords: ['flag', 'armenia', '🇦🇲'] },
  '🇦🇼': { name: 'flag: Aruba', keywords: ['flag', 'aruba', '🇦🇼'] },
  '🇦🇺': { name: 'flag: Australia', keywords: ['flag', 'australia', '🇦🇺'] },
  '🇦🇹': { name: 'flag: Austria', keywords: ['flag', 'austria', '🇦🇹'] },
  '🇦🇿': { name: 'flag: Azerbaijan', keywords: ['flag', 'azerbaijan', '🇦🇿'] },
  '🇧🇸': { name: 'flag: Bahamas', keywords: ['flag', 'bahamas', '🇧🇸'] },
  '🇧🇭': { name: 'flag: Bahrain', keywords: ['flag', 'bahrain', '🇧🇭'] },
  '🇧🇩': { name: 'flag: Bangladesh', keywords: ['flag', 'bangladesh', '🇧🇩'] },
  '🇧🇧': { name: 'flag: Barbados', keywords: ['flag', 'barbados', '🇧🇧'] },
  '🇧🇾': { name: 'flag: Belarus', keywords: ['flag', 'belarus', '🇧🇾'] },
  '🇧🇪': { name: 'flag: Belgium', keywords: ['flag', 'belgium', '🇧🇪'] },
  '🇧🇿': { name: 'flag: Belize', keywords: ['flag', 'belize', '🇧🇿'] },
  '🇧🇯': { name: 'flag: Benin', keywords: ['flag', 'benin', '🇧🇯'] },
  '🇧🇲': { name: 'flag: Bermuda', keywords: ['flag', 'bermuda', '🇧🇲'] },
  '🇧🇹': { name: 'flag: Bhutan', keywords: ['flag', 'bhutan', '🇧🇹'] },
  '🇧🇴': { name: 'flag: Bolivia', keywords: ['flag', 'bolivia', '🇧🇴'] },
  '🇧🇦': { name: 'flag: Bosnia & Herzegovina', keywords: ['flag', 'bosnia', 'herzegovina', '🇧🇦'] },
  '🇧🇼': { name: 'flag: Botswana', keywords: ['flag', 'botswana', '🇧🇼'] },
  '🇧🇷': { name: 'flag: Brazil', keywords: ['flag', 'brazil', '🇧🇷'] },
  '🇮🇴': { name: 'flag: British Indian Ocean Territory', keywords: ['flag', 'british indian ocean territory', '🇮🇴'] },
  '🇻🇬': { name: 'flag: British Virgin Islands', keywords: ['flag', 'british virgin islands', '🇻🇬'] },
  '🇧🇳': { name: 'flag: Brunei', keywords: ['flag', 'brunei', '🇧🇳'] },
  '🇧🇬': { name: 'flag: Bulgaria', keywords: ['flag', 'bulgaria', '🇧🇬'] },
  '🇧🇫': { name: 'flag: Burkina Faso', keywords: ['flag', 'burkina faso', '🇧🇫'] },
  '🇧🇮': { name: 'flag: Burundi', keywords: ['flag', 'burundi', '🇧🇮'] },
  '🇰🇭': { name: 'flag: Cambodia', keywords: ['flag', 'cambodia', '🇰🇭'] },
  '🇨🇲': { name: 'flag: Cameroon', keywords: ['flag', 'cameroon', '🇨🇲'] },
  '🇨🇦': { name: 'flag: Canada', keywords: ['flag', 'canada', '🇨🇦'] },
  '🇮🇨': { name: 'flag: Canary Islands', keywords: ['flag', 'canary islands', '🇮🇨'] },
  '🇨🇻': { name: 'flag: Cape Verde', keywords: ['flag', 'cape verde', '🇨🇻'] },
  '🇧🇶': { name: 'flag: Caribbean Netherlands', keywords: ['flag', 'caribbean netherlands', '🇧🇶'] },
  '🇰🇾': { name: 'flag: Cayman Islands', keywords: ['flag', 'cayman islands', '🇰🇾'] },
  '🇨🇫': { name: 'flag: Central African Republic', keywords: ['flag', 'central african republic', '🇨🇫'] },
  '🇹🇩': { name: 'flag: Chad', keywords: ['flag', 'chad', '🇹🇩'] },
  '🇨🇱': { name: 'flag: Chile', keywords: ['flag', 'chile', '🇨🇱'] },
  '🇨🇳': { name: 'flag: China', keywords: ['flag', 'china', '🇨🇳'] },
  '🇨🇽': { name: 'flag: Christmas Island', keywords: ['flag', 'christmas island', '🇨🇽'] },
  '🇨🇨': { name: 'flag: Cocos (Keeling) Islands', keywords: ['flag', 'cocos islands', '🇨🇨'] },
  '🇨🇴': { name: 'flag: Colombia', keywords: ['flag', 'colombia', '🇨🇴'] },
  '🇰🇲': { name: 'flag: Comoros', keywords: ['flag', 'comoros', '🇰🇲'] },
  '🇨🇬': { name: 'flag: Congo - Brazzaville', keywords: ['flag', 'congo', 'brazzaville', '🇨🇬'] },
  '🇨🇩': { name: 'flag: Congo - Kinshasa', keywords: ['flag', 'congo', 'kinshasa', '🇨🇩'] },
  '🇨🇰': { name: 'flag: Cook Islands', keywords: ['flag', 'cook islands', '🇨🇰'] },
  '🇨🇷': { name: 'flag: Costa Rica', keywords: ['flag', 'costa rica', '🇨🇷'] },
  '🇨🇮': { name: 'flag: Côte d\'Ivoire', keywords: ['flag', 'cote divoire', 'ivory coast', '🇨🇮'] },
  '🇭🇷': { name: 'flag: Croatia', keywords: ['flag', 'croatia', '🇭🇷'] },
  '🇨🇺': { name: 'flag: Cuba', keywords: ['flag', 'cuba', '🇨🇺'] },
  '🇨🇼': { name: 'flag: Curaçao', keywords: ['flag', 'curacao', '🇨🇼'] },
  '🇨🇾': { name: 'flag: Cyprus', keywords: ['flag', 'cyprus', '🇨🇾'] },
  '🇨🇿': { name: 'flag: Czechia', keywords: ['flag', 'czechia', 'czech republic', '🇨🇿'] },
  '🇩🇰': { name: 'flag: Denmark', keywords: ['flag', 'denmark', '🇩🇰'] },
  '🇩🇯': { name: 'flag: Djibouti', keywords: ['flag', 'djibouti', '🇩🇯'] },
  '🇩🇲': { name: 'flag: Dominica', keywords: ['flag', 'dominica', '🇩🇲'] },
  '🇩🇴': { name: 'flag: Dominican Republic', keywords: ['flag', 'dominican republic', '🇩🇴'] },
  '🇪🇨': { name: 'flag: Ecuador', keywords: ['flag', 'ecuador', '🇪🇨'] },
  '🇪🇬': { name: 'flag: Egypt', keywords: ['flag', 'egypt', '🇪🇬'] },
  '🇸🇻': { name: 'flag: El Salvador', keywords: ['flag', 'el salvador', '🇸🇻'] },
  '🇬🇶': { name: 'flag: Equatorial Guinea', keywords: ['flag', 'equatorial guinea', '🇬🇶'] },
  '🇪🇷': { name: 'flag: Eritrea', keywords: ['flag', 'eritrea', '🇪🇷'] },
  '🇪🇪': { name: 'flag: Estonia', keywords: ['flag', 'estonia', '🇪🇪'] },
  '🇪🇹': { name: 'flag: Ethiopia', keywords: ['flag', 'ethiopia', '🇪🇹'] },
  '🇪🇺': { name: 'flag: European Union', keywords: ['flag', 'european union', 'eu', '🇪🇺'] },
  '🇫🇰': { name: 'flag: Falkland Islands', keywords: ['flag', 'falkland islands', '🇫🇰'] },
  '🇫🇴': { name: 'flag: Faroe Islands', keywords: ['flag', 'faroe islands', '🇫🇴'] },
  '🇫🇯': { name: 'flag: Fiji', keywords: ['flag', 'fiji', '🇫🇯'] },
  '🇫🇮': { name: 'flag: Finland', keywords: ['flag', 'finland', '🇫🇮'] },
  '🇫🇷': { name: 'flag: France', keywords: ['flag', 'france', '🇫🇷'] },
  '🇬🇫': { name: 'flag: French Guiana', keywords: ['flag', 'french guiana', '🇬🇫'] },
  '🇵🇫': { name: 'flag: French Polynesia', keywords: ['flag', 'french polynesia', '🇵🇫'] },
  '🇹🇫': { name: 'flag: French Southern Territories', keywords: ['flag', 'french southern territories', '🇹🇫'] },
  '🇬🇦': { name: 'flag: Gabon', keywords: ['flag', 'gabon', '🇬🇦'] },
  '🇬🇲': { name: 'flag: Gambia', keywords: ['flag', 'gambia', '🇬🇲'] },
  '🇬🇪': { name: 'flag: Georgia', keywords: ['flag', 'georgia', '🇬🇪'] },
  '🇩🇪': { name: 'flag: Germany', keywords: ['flag', 'germany', '🇩🇪'] },
  '🇬🇭': { name: 'flag: Ghana', keywords: ['flag', 'ghana', '🇬🇭'] },
  '🇬🇮': { name: 'flag: Gibraltar', keywords: ['flag', 'gibraltar', '🇬🇮'] },
  '🇬🇷': { name: 'flag: Greece', keywords: ['flag', 'greece', '🇬🇷'] },
  '🇬🇱': { name: 'flag: Greenland', keywords: ['flag', 'greenland', '🇬🇱'] },
  '🇬🇩': { name: 'flag: Grenada', keywords: ['flag', 'grenada', '🇬🇩'] },
  '🇬🇵': { name: 'flag: Guadeloupe', keywords: ['flag', 'guadeloupe', '🇬🇵'] },
  '🇬🇺': { name: 'flag: Guam', keywords: ['flag', 'guam', '🇬🇺'] },
  '🇬🇹': { name: 'flag: Guatemala', keywords: ['flag', 'guatemala', '🇬🇹'] },
  '🇬🇬': { name: 'flag: Guernsey', keywords: ['flag', 'guernsey', '🇬🇬'] },
  '🇬🇳': { name: 'flag: Guinea', keywords: ['flag', 'guinea', '🇬🇳'] },
  '🇬🇼': { name: 'flag: Guinea-Bissau', keywords: ['flag', 'guinea bissau', '🇬🇼'] },
  '🇬🇾': { name: 'flag: Guyana', keywords: ['flag', 'guyana', '🇬🇾'] },
  '🇭🇹': { name: 'flag: Haiti', keywords: ['flag', 'haiti', '🇭🇹'] },
  '🇭🇳': { name: 'flag: Honduras', keywords: ['flag', 'honduras', '🇭🇳'] },
  '🇭🇰': { name: 'flag: Hong Kong SAR China', keywords: ['flag', 'hong kong', '🇭🇰'] },
  '🇭🇺': { name: 'flag: Hungary', keywords: ['flag', 'hungary', '🇭🇺'] },
  '🇮🇸': { name: 'flag: Iceland', keywords: ['flag', 'iceland', '🇮🇸'] },
  '🇮🇳': { name: 'flag: India', keywords: ['flag', 'india', '🇮🇳'] },
  '🇮🇩': { name: 'flag: Indonesia', keywords: ['flag', 'indonesia', '🇮🇩'] },
  '🇮🇷': { name: 'flag: Iran', keywords: ['flag', 'iran', '🇮🇷'] },
  '🇮🇶': { name: 'flag: Iraq', keywords: ['flag', 'iraq', '🇮🇶'] },
  '🇮🇪': { name: 'flag: Ireland', keywords: ['flag', 'ireland', '🇮🇪'] },
  '🇮🇲': { name: 'flag: Isle of Man', keywords: ['flag', 'isle of man', '🇮🇲'] },
  '🇮🇱': { name: 'flag: Israel', keywords: ['flag', 'israel', '🇮🇱'] },
  '🇮🇹': { name: 'flag: Italy', keywords: ['flag', 'italy', '🇮🇹'] },
  '🇯🇲': { name: 'flag: Jamaica', keywords: ['flag', 'jamaica', '🇯🇲'] },
  '🇯🇵': { name: 'flag: Japan', keywords: ['flag', 'japan', '🇯🇵'] },
  '🇯🇪': { name: 'flag: Jersey', keywords: ['flag', 'jersey', '🇯🇪'] },
  '🇯🇴': { name: 'flag: Jordan', keywords: ['flag', 'jordan', '🇯🇴'] },
  '🇰🇿': { name: 'flag: Kazakhstan', keywords: ['flag', 'kazakhstan', '🇰🇿'] },
  '🇰🇪': { name: 'flag: Kenya', keywords: ['flag', 'kenya', '🇰🇪'] },
  '🇰🇮': { name: 'flag: Kiribati', keywords: ['flag', 'kiribati', '🇰🇮'] },
  '🇽🇰': { name: 'flag: Kosovo', keywords: ['flag', 'kosovo', '🇽🇰'] },
  '🇰🇼': { name: 'flag: Kuwait', keywords: ['flag', 'kuwait', '🇰🇼'] },
  '🇰🇬': { name: 'flag: Kyrgyzstan', keywords: ['flag', 'kyrgyzstan', '🇰🇬'] },
  '🇱🇦': { name: 'flag: Laos', keywords: ['flag', 'laos', '🇱🇦'] },
  '🇱🇻': { name: 'flag: Latvia', keywords: ['flag', 'latvia', '🇱🇻'] },
  '🇱🇧': { name: 'flag: Lebanon', keywords: ['flag', 'lebanon', '🇱🇧'] },
  '🇱🇸': { name: 'flag: Lesotho', keywords: ['flag', 'lesotho', '🇱🇸'] },
  '🇱🇷': { name: 'flag: Liberia', keywords: ['flag', 'liberia', '🇱🇷'] },
  '🇱🇾': { name: 'flag: Libya', keywords: ['flag', 'libya', '🇱🇾'] },
  '🇱🇮': { name: 'flag: Liechtenstein', keywords: ['flag', 'liechtenstein', '🇱🇮'] },
  '🇱🇹': { name: 'flag: Lithuania', keywords: ['flag', 'lithuania', '🇱🇹'] },
  '🇱🇺': { name: 'flag: Luxembourg', keywords: ['flag', 'luxembourg', '🇱🇺'] },
  '🇲🇴': { name: 'flag: Macao SAR China', keywords: ['flag', 'macao', '🇲🇴'] },
  '🇲🇰': { name: 'flag: North Macedonia', keywords: ['flag', 'north macedonia', '🇲🇰'] },
  '🇲🇬': { name: 'flag: Madagascar', keywords: ['flag', 'madagascar', '🇲🇬'] },
  '🇲🇼': { name: 'flag: Malawi', keywords: ['flag', 'malawi', '🇲🇼'] },
  '🇲🇾': { name: 'flag: Malaysia', keywords: ['flag', 'malaysia', '🇲🇾'] },
  '🇲🇻': { name: 'flag: Maldives', keywords: ['flag', 'maldives', '🇲🇻'] },
  '🇲🇱': { name: 'flag: Mali', keywords: ['flag', 'mali', '🇲🇱'] },
  '🇲🇹': { name: 'flag: Malta', keywords: ['flag', 'malta', '🇲🇹'] },
  '🇲🇭': { name: 'flag: Marshall Islands', keywords: ['flag', 'marshall islands', '🇲🇭'] },
  '🇲🇶': { name: 'flag: Martinique', keywords: ['flag', 'martinique', '🇲🇶'] },
  '🇲🇷': { name: 'flag: Mauritania', keywords: ['flag', 'mauritania', '🇲🇷'] },
  '🇲🇺': { name: 'flag: Mauritius', keywords: ['flag', 'mauritius', '🇲🇺'] },
  '🇾🇹': { name: 'flag: Mayotte', keywords: ['flag', 'mayotte', '🇾🇹'] },
  '🇲🇽': { name: 'flag: Mexico', keywords: ['flag', 'mexico', '🇲🇽'] },
  '🇫🇲': { name: 'flag: Micronesia', keywords: ['flag', 'micronesia', '🇫🇲'] },
  '🇲🇩': { name: 'flag: Moldova', keywords: ['flag', 'moldova', '🇲🇩'] },
  '🇲🇨': { name: 'flag: Monaco', keywords: ['flag', 'monaco', '🇲🇨'] },
  '🇲🇳': { name: 'flag: Mongolia', keywords: ['flag', 'mongolia', '🇲🇳'] },
  '🇲🇪': { name: 'flag: Montenegro', keywords: ['flag', 'montenegro', '🇲🇪'] },
  '🇲🇸': { name: 'flag: Montserrat', keywords: ['flag', 'montserrat', '🇲🇸'] },
  '🇲🇦': { name: 'flag: Morocco', keywords: ['flag', 'morocco', '🇲🇦'] },
  '🇲🇿': { name: 'flag: Mozambique', keywords: ['flag', 'mozambique', '🇲🇿'] },
  '🇲🇲': { name: 'flag: Myanmar (Burma)', keywords: ['flag', 'myanmar', 'burma', '🇲🇲'] },
  '🇳🇦': { name: 'flag: Namibia', keywords: ['flag', 'namibia', '🇳🇦'] },
  '🇳🇷': { name: 'flag: Nauru', keywords: ['flag', 'nauru', '🇳🇷'] },
  '🇳🇵': { name: 'flag: Nepal', keywords: ['flag', 'nepal', '🇳🇵'] },
  '🇳🇱': { name: 'flag: Netherlands', keywords: ['flag', 'netherlands', '🇳🇱'] },
  '🇳🇨': { name: 'flag: New Caledonia', keywords: ['flag', 'new caledonia', '🇳🇨'] },
  '🇳🇿': { name: 'flag: New Zealand', keywords: ['flag', 'new zealand', '🇳🇿'] },
  '🇳🇮': { name: 'flag: Nicaragua', keywords: ['flag', 'nicaragua', '🇳🇮'] },
  '🇳🇪': { name: 'flag: Niger', keywords: ['flag', 'niger', '🇳🇪'] },
  '🇳🇬': { name: 'flag: Nigeria', keywords: ['flag', 'nigeria', '🇳🇬'] },
  '🇳🇺': { name: 'flag: Niue', keywords: ['flag', 'niue', '🇳🇺'] },
  '🇳🇫': { name: 'flag: Norfolk Island', keywords: ['flag', 'norfolk island', '🇳🇫'] },
  '🇰🇵': { name: 'flag: North Korea', keywords: ['flag', 'north korea', '🇰🇵'] },
  '🇲🇵': { name: 'flag: Northern Mariana Islands', keywords: ['flag', 'northern mariana islands', '🇲🇵'] },
  '🇳🇴': { name: 'flag: Norway', keywords: ['flag', 'norway', '🇳🇴'] },
  '🇴🇲': { name: 'flag: Oman', keywords: ['flag', 'oman', '🇴🇲'] },
  '🇵🇰': { name: 'flag: Pakistan', keywords: ['flag', 'pakistan', '🇵🇰'] },
  '🇵🇼': { name: 'flag: Palau', keywords: ['flag', 'palau', '🇵🇼'] },
  '🇵🇸': { name: 'flag: Palestinian Territories', keywords: ['flag', 'palestinian territories', '🇵🇸'] },
  '🇵🇦': { name: 'flag: Panama', keywords: ['flag', 'panama', '🇵🇦'] },
  '🇵🇬': { name: 'flag: Papua New Guinea', keywords: ['flag', 'papua new guinea', '🇵🇬'] },
  '🇵🇾': { name: 'flag: Paraguay', keywords: ['flag', 'paraguay', '🇵🇾'] },
  '🇵🇪': { name: 'flag: Peru', keywords: ['flag', 'peru', '🇵🇪'] },
  '🇵🇭': { name: 'flag: Philippines', keywords: ['flag', 'philippines', '🇵🇭'] },
  '🇵🇳': { name: 'flag: Pitcairn Islands', keywords: ['flag', 'pitcairn islands', '🇵🇳'] },
  '🇵🇱': { name: 'flag: Poland', keywords: ['flag', 'poland', '🇵🇱'] },
  '🇵🇹': { name: 'flag: Portugal', keywords: ['flag', 'portugal', '🇵🇹'] },
  '🇵🇷': { name: 'flag: Puerto Rico', keywords: ['flag', 'puerto rico', '🇵🇷'] },
  '🇶🇦': { name: 'flag: Qatar', keywords: ['flag', 'qatar', '🇶🇦'] },
  '🇷🇪': { name: 'flag: Réunion', keywords: ['flag', 'reunion', '🇷🇪'] },
  '🇷🇴': { name: 'flag: Romania', keywords: ['flag', 'romania', '🇷🇴'] },
  '🇷🇺': { name: 'flag: Russia', keywords: ['flag', 'russia', '🇷🇺'] },
  '🇷🇼': { name: 'flag: Rwanda', keywords: ['flag', 'rwanda', '🇷🇼'] },
  '🇼🇸': { name: 'flag: Samoa', keywords: ['flag', 'samoa', '🇼🇸'] },
  '🇸🇲': { name: 'flag: San Marino', keywords: ['flag', 'san marino', '🇸🇲'] },
  '🇸🇦': { name: 'flag: Saudi Arabia', keywords: ['flag', 'saudi arabia', '🇸🇦'] },
  '🇸🇳': { name: 'flag: Senegal', keywords: ['flag', 'senegal', '🇸🇳'] },
  '🇷🇸': { name: 'flag: Serbia', keywords: ['flag', 'serbia', '🇷🇸'] },
  '🇸🇨': { name: 'flag: Seychelles', keywords: ['flag', 'seychelles', '🇸🇨'] },
  '🇸🇱': { name: 'flag: Sierra Leone', keywords: ['flag', 'sierra leone', '🇸🇱'] },
  '🇸🇬': { name: 'flag: Singapore', keywords: ['flag', 'singapore', '🇸🇬'] },
  '🇸🇽': { name: 'flag: Sint Maarten', keywords: ['flag', 'sint maarten', '🇸🇽'] },
  '🇸🇰': { name: 'flag: Slovakia', keywords: ['flag', 'slovakia', '🇸🇰'] },
  '🇸🇮': { name: 'flag: Slovenia', keywords: ['flag', 'slovenia', '🇸🇮'] },
  '🇬🇸': { name: 'flag: South Georgia & South Sandwich Islands', keywords: ['flag', 'south georgia', 'south sandwich islands', '🇬🇸'] },
  '🇸🇧': { name: 'flag: Solomon Islands', keywords: ['flag', 'solomon islands', '🇸🇧'] },
  '🇸🇴': { name: 'flag: Somalia', keywords: ['flag', 'somalia', '🇸🇴'] },
  '🇿🇦': { name: 'flag: South Africa', keywords: ['flag', 'south africa', '🇿🇦'] },
  '🇰🇷': { name: 'flag: South Korea', keywords: ['flag', 'south korea', '🇰🇷'] },
  '🇸🇸': { name: 'flag: South Sudan', keywords: ['flag', 'south sudan', '🇸🇸'] },
  '🇪🇸': { name: 'flag: Spain', keywords: ['flag', 'spain', '🇪🇸'] },
  '🇱🇰': { name: 'flag: Sri Lanka', keywords: ['flag', 'sri lanka', '🇱🇰'] },
  '🇧🇱': { name: 'flag: St. Barthélemy', keywords: ['flag', 'st barthélemy', '🇧🇱'] },
  '🇸🇭': { name: 'flag: St. Helena', keywords: ['flag', 'st helena', '🇸🇭'] },
  '🇰🇳': { name: 'flag: St. Kitts & Nevis', keywords: ['flag', 'st kitts', 'nevis', '🇰🇳'] },
  '🇱🇨': { name: 'flag: St. Lucia', keywords: ['flag', 'st lucia', '🇱🇨'] },
  '🇵🇲': { name: 'flag: St. Pierre & Miquelon', keywords: ['flag', 'st pierre', 'miquelon', '🇵🇲'] },
  '🇻🇨': { name: 'flag: St. Vincent & Grenadines', keywords: ['flag', 'st vincent', 'grenadines', '🇻🇨'] },
  '🇸🇩': { name: 'flag: Sudan', keywords: ['flag', 'sudan', '🇸🇩'] },
  '🇸🇷': { name: 'flag: Suriname', keywords: ['flag', 'suriname', '🇸🇷'] },
  '🇸🇿': { name: 'flag: Eswatini', keywords: ['flag', 'eswatini', '🇸🇿'] },
  '🇸🇪': { name: 'flag: Sweden', keywords: ['flag', 'sweden', '🇸🇪'] },
  '🇨🇭': { name: 'flag: Switzerland', keywords: ['flag', 'switzerland', '🇨🇭'] },
  '🇸🇾': { name: 'flag: Syria', keywords: ['flag', 'syria', '🇸🇾'] },
  '🇹🇼': { name: 'flag: Taiwan', keywords: ['flag', 'taiwan', '🇹🇼'] },
  '🇹🇯': { name: 'flag: Tajikistan', keywords: ['flag', 'tajikistan', '🇹🇯'] },
  '🇹🇿': { name: 'flag: Tanzania', keywords: ['flag', 'tanzania', '🇹🇿'] },
  '🇹🇭': { name: 'flag: Thailand', keywords: ['flag', 'thailand', '🇹🇭'] },
  '🇹🇱': { name: 'flag: Timor-Leste', keywords: ['flag', 'timor-leste', '🇹🇱'] },
  '🇹🇬': { name: 'flag: Togo', keywords: ['flag', 'togo', '🇹🇬'] },
  '🇹🇰': { name: 'flag: Tokelau', keywords: ['flag', 'tokelau', '🇹🇰'] },
  '🇹🇴': { name: 'flag: Tonga', keywords: ['flag', 'tonga', '🇹🇴'] },
  '🇹🇹': { name: 'flag: Trinidad & Tobago', keywords: ['flag', 'trinidad', 'tobago', '🇹🇹'] },
  '🇹🇳': { name: 'flag: Tunisia', keywords: ['flag', 'tunisia', '🇹🇳'] },
  '🇹🇷': { name: 'flag: Turkey', keywords: ['flag', 'turkey', '🇹🇷'] },
  '🇹🇲': { name: 'flag: Turkmenistan', keywords: ['flag', 'turkmenistan', '🇹🇲'] },
  '🇹🇨': { name: 'flag: Turks & Caicos Islands', keywords: ['flag', 'turks', 'caicos islands', '🇹🇨'] },
  '🇹🇻': { name: 'flag: Tuvalu', keywords: ['flag', 'tuvalu', '🇹🇻'] },
  '🇻🇮': { name: 'flag: U.S. Virgin Islands', keywords: ['flag', 'us virgin islands', '🇻🇮'] },
  '🇺🇬': { name: 'flag: Uganda', keywords: ['flag', 'uganda', '🇺🇬'] },
  '🇺🇦': { name: 'flag: Ukraine', keywords: ['flag', 'ukraine', '🇺🇦'] },
  '🇦🇪': { name: 'flag: United Arab Emirates', keywords: ['flag', 'united arab emirates', '🇦🇪'] },
  '🇬🇧': { name: 'flag: United Kingdom', keywords: ['flag', 'united kingdom', '🇬🇧'] },
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿': { name: 'flag: England', keywords: ['flag', 'england', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'] },
  '🏴󠁧󠁢󠁳󠁣󠁴󠁿': { name: 'flag: Scotland', keywords: ['flag', 'scotland', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'] },
  '🏴󠁧󠁢󠁷󠁬󠁳󠁿': { name: 'flag: Wales', keywords: ['flag', 'wales', '🏴󠁧󠁢󠁷󠁬󠁳󠁿'] },
  '🇺🇸': { name: 'flag: United States', keywords: ['flag', 'united states', '🇺🇸'] },
  '🇺🇾': { name: 'flag: Uruguay', keywords: ['flag', 'uruguay', '🇺🇾'] },
  '🇺🇿': { name: 'flag: Uzbekistan', keywords: ['flag', 'uzbekistan', '🇺🇿'] },
  '🇻🇺': { name: 'flag: Vanuatu', keywords: ['flag', 'vanuatu', '🇻🇺'] },
  '🇻🇦': { name: 'flag: Vatican City', keywords: ['flag', 'vatican city', '🇻🇦'] },
  '🇻🇪': { name: 'flag: Venezuela', keywords: ['flag', 'venezuela', '🇻🇪'] },
  '🇻🇳': { name: 'flag: Vietnam', keywords: ['flag', 'vietnam', '🇻🇳'] },
  '🇼🇫': { name: 'flag: Wallis & Futuna', keywords: ['flag', 'wallis', 'futuna', '🇼🇫'] },
  '🇪🇭': { name: 'flag: Western Sahara', keywords: ['flag', 'western sahara', '🇪🇭'] },
  '🇾🇪': { name: 'flag: Yemen', keywords: ['flag', 'yemen', '🇾🇪'] },
  '🇿🇲': { name: 'flag: Zambia', keywords: ['flag', 'zambia', '🇿🇲'] },
  '🇿🇼': { name: 'flag: Zimbabwe', keywords: ['flag', 'zimbabwe', '🇿🇼'] },
}; 